### ISSUE TITLE
Task: add dates (start, expiration) to admin config policies

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1009]
We need to add start date and expiration date to the policy definition. 
Does OPA support effective and expiration dates in policies? If not, we will need to decide whether to contribute that capability to OPA or address it in our code.

**Comment by roee88** [comment]
Can you elaborate on what exactly you envision? Preferably compared to having a condition that checks for time/date in the rule (or in a top-level rule of a rego file if you consider a file as a policy rather than a rule as a policy).


Cross ref: https://github.com/open-policy-agent/opa/issues/519

**Comment by shlomitk1** [comment]
Checking the date in the rule body could work. @simanadler - what do you think?
