### ISSUE TITLE
Task: develop a mechanism for uploading new admin config policy files and tracking the changes

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1010]
Background: to save time, rego files are not compiled on each policy evaluation. This requires us to monitor the changes and re-compile accordingly.
Proposal: check creation/update dates of the rego files and re-compile if the dates are after the last compile.

**Comment by shlomitk1** [comment]
Proposed framework for deploying/modifying admin config policies:
- charts/fybrik/files/adminconfig include only out-of-the-box policies, i.e. default_policies.rego
- Fybrik helm release is installed with the default policies only
-  Additional policies, infrastructure files are added. Could happen as the next step in Fybrik setup process, or at the run time (addition/modification/deletion of policies and infrastructure files).  Process of deploying/replacing policy/infrastructure files:
   mkdir /tmp/adminconfig
   cp charts/fybrik/files/adminconfig/* /tmp/adminconfig/
   cp <policy and infrastructure files> /tmp/adminconfig/
   kubectl create configmap fybrik-adminconfig --from-file=/tmp/adminconfig -o yaml --dry-run=client | kubectl replace -f -
   
After `fybrik-adminconfig` configmap is updated with the new version, the files will be propagated into /tmp/adminconfig directory of the manager pod (in a minute or so after the change).
Manager would
1. Store the last compile timestamp.
2. On each evaluation, compare the last compile timestamp with the file update/creation timestamp, recompile if necessary.

**Comment by simanadler** [comment]
I think it's be important to add versions to the policies, especially if we are now enabling dynamic updates to the config policy files.

**Comment by shlomitk1** [comment]
> I think it's be important to add versions to the policies, especially if we are now enabling dynamic updates to the config policy files.

Suggestion: to provide a rego file that specifies `version` (together with Fybrik deployment). Whenever the admin needs to modify the policies, the version file will be modified accordingly. Manager will log the policies' version for audit.
