### ISSUE TITLE
Follow-up tasks on logging

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1035]
Follow-up tasks:
1. Change label to fybrik-application-uuid instead of FybrikApplicationUUID.
2. Do not recommend using Fatal level in documentation.
3. Add uuid to unit tests, it is currently empty.
4. Add uuid to adminconfig policy evaluator (no value is currently passed to the evaluator input)

**Comment by simanadler** [comment]
Regarding #2 this is true for the controller, but the logging is meant to be used by data plane components, connectors, etc as well.  It is up to them whether using fatal makes sense to them.

With the rest I agree.  However, I suggest adding this to the issue that we already have and closing this issue.  https://github.com/fybrik/fybrik/issues/926

**Comment by shlomitk1** [comment]
OK. Closing.
