### ISSUE TITLE
Feature: provision a bucket dynamically

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#104]
https://docs.google.com/document/d/1PzaQtED9NUq10REfxl0wMFOl247SKc0XvAUHpxjSYjY/edit?usp=sharing

When implicit copy is applied, the mesh for data needs to provide a bucket for copy destination. Currently, a single bucket is created manually, and the bucket credentials are stored in vault manually as well. 
Requirement: to provision a bucket dynamically when copy is required, to manage the bucket life cycle together with its credentials.

**Comment by simanadler** [comment]
@shlomitk1 I think this issue needs to be a bit broader.  For the ingest flow (a future feature) we will also need to dynamically allocate storage.  In general I think the full scope of this task is as follows, although we will of course need to implement it gradually.

* IT person needs to somehow inform the M4D of the available storage accounts, their types, and the credentials for accessing them.  Cloud object store (COS) are one example, but there will be other types such as databases, etc.

When storage is required (temporary for implicit copy, or more permanent for the ingest scenario) M4D manager needs to allocate the appropriate storage in the relevant type of data store, ex: buckets in COS, in an account pre-allocated by the enterprise IT team.

As for the life cycle of the allocated bucket (or other type of storage) ...
* For implicit copy, M4D manager should release both the data and the bucket when the processing is complete - i.e. the M4DApplication instance is deleted
* For data that was ingested into the data lake (and cataloged in the Data Catalog during the process), there will have to be a separate flow for removing data from the data lake.  This is a future feature.  

@roee88 @ronenkat This is related to the DLF discussions

**Comment by shlomitk1** [comment]
Things left to do:
- fix marking buckets as persistent (dependency on DLF)
- support multiple endpoints/regions for a single account
- check errors of deleting a dataset, ensure that m4dapplication deletion is not blocked
- analyze Dataset errors
- Register secret in vault - move to pkg/vault

**Comment by shlomitk1** [comment]
Implemented.
