### ISSUE TITLE
Support data source that comes directly from another module

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1047]
Use-case we want to support: module A reads an asset from a data store, e.g. s3. Module B gets data from module A via an exposed endpoint(?) in order to process the data.
Blueprint receives DataStore as an argument:
```
type DataStore struct {
	// Holds details for retrieving credentials by the modules from Vault store.
	// It is a map so that different credentials can be stored for the different DataFlow operations.
	Vault map[string]Vault `json:"vault"`
	// Connection has the relevant details for accesing the data (url, table, ssl, etc.)
	// +required
	Connection *serde.Arbitrary `json:"connection"`
	// Format represents data format (e.g. parquet) as received from catalog connectors
	// +required
	Format string `json:"format"`
}
```

Plotter defines `StepSource` that either leads to a physical data store of an assert, or `Service ` of data provider:
```
// Service holds information for accessing a module instance
type Service struct {
	//+required
	Endpoint EndpointSpec `json:"endpoint"`

	// Format represents data format (e.g. parquet) as received from catalog connectors
	// +required
	Format string `json:"format"`
}

// StepSource is the source of this step: it could be assetID
// or an enpoint of another step
type StepSource struct {
	// AssetID identifies the source asset of this step
	// +optional
	AssetID string `json:"assetId,omitempty"`

	//+optional
	API *Service `json:"api,omitempty"`
}
```
Currently, there is no way to connect StepSource to DataStore inside a blueprint.

**Comment by roee88** [comment]
This also holds to the endpoint reported in FybrikApplication status. It seems like these should all use Connection instead (or details to also include format).

**Comment by shlomitk1** [comment]
I suggest to use Connection of type/name "endpoint" with additional properties currently defined in EndpointSpec.
The change will take place in FybrikApplication status and Plotter (instead of Service). 
Do we want to replace EndpointSpec in FybrikModule definition as well?
