### ISSUE TITLE
Add taxonomy and API structures as code 

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#1049]
During the work on taxonomy we hit some drawbacks of using the generated code, like the inability to properly use these structures in CRDs and difficulties in defining a single source of truth for the definitions.

To address these and simplify the taxonomy related parts of the repo:

- [x] Add the taxonomy and API structures as code to `pkg/model` (i.e. the model code) #1051
- [x] Use the model code to generate the JSON schemas (base taxonomy.json, catalog and policy manager)  https://github.com/fybrik/fybrik/pull/1060
- [x] Use the model code in manager #1054
- [x] Use the model code in opa connector
- [x] Use the model code in katalog connector
- [x] Remove the old generated code https://github.com/fybrik/fybrik/pull/1061
- [ ] Update docs
- [x] Change the `taxonomy validate` command to validate custom `taxonomy.json` files (and replace the legacy unit test for it) https://github.com/fybrik/fybrik/pull/1065
- [x] Remove the use of openapi2crd and archive its repo (partially https://github.com/fybrik/fybrik/pull/1065)
- [x] Remove the generate target from manager/Makefile https://github.com/fybrik/fybrik/pull/1082
- [ ] Review all taxonomy model definitions

Later we can do the same for CRDs
- #1091

Note: We may in the future try to use something like https://github.com/kubernetes/kube-openapi for the schema generation but for now to keep things more aligned with our current schemas  https://github.com/fybrik/json-schema-generator will be used.

**Comment by simanadler** [comment]
Is there clear documentation in the website about this - both in terms of they why and the how?

**Comment by roee88** [comment]
There is minimal documentation in https://fybrik.io/v0.5/tasks/custom-taxonomy/.
There are related open issues in https://github.com/fybrik/fybrik/issues/792 and https://github.com/fybrik/fybrik/issues/779.
There is an `Update docs` task in this issue. 

Please be clearer on the ask.

**Comment by simanadler** [comment]
@roee88 I suggest we add a section in https://fybrik.io/v0.5/concepts/introduction/ about taxonomy - i.e. why it's needed, and how it is used.

**Comment by roee88** [comment]
Documentation will be addressed as part of #779
