### ISSUE TITLE
Asset connection type of db2 crashes the katalog connector

### ISSUE THREAD

**Issue by elsalant** [fybrik/fybrik#1074]
Using a connect.type of db2 for an asset causes the katalog connector to crash.  
According to the documentation in https://fybrik.io/v0.5/reference/crds/#assetspecassetdetailsconnectiondb2, no additional parameters are required for the connection structure.

**Asset definition:**
apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: observation-json
  namespace: sql-fhir
spec:
  secretRef: 
    name: "" 
  assetDetails:
    dataFormat: json
    connection:
      type: db2
  assetMetadata:
    geography: UK
    tags:
    - healthcare
    componentsMetadata:
      id:
        tags:
        - PII

eliot@Eliots-MacBook-Pro sqlToFHIR % kubectl logs katalog-connector-8454d557c5-snvgg -n fybrik-system
I1229 11:16:37.519732       1 request.go:668] Waited for 1.0387151s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/csi.storage.k8s.io/v1alpha1?timeout=32s
2021/12/29 11:17:55 In GetDatasetInfo: asset namespace is sql-fhir asset name is observation-json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13f4c07]

goroutine 167 [running]:
fybrik.io/fybrik/connectors/katalog/pkg/connector.buildDataStore(0xc00035b680, 0xc0004b5590, 0x18ad280, 0xc0001c4070)
	/home/runner/work/fybrik/fybrik/connectors/katalog/pkg/connector/catalog.go:127 +0x307
fybrik.io/fybrik/connectors/katalog/pkg/connector.(*DataCatalogService).GetDatasetInfo(0xc00033a9a0, 0x189ce60, 0xc0004b5590, 0xc000125310, 0xc00033a9a0, 0xc0004b5590, 0xc000015ba0)
	/home/runner/work/fybrik/fybrik/connectors/katalog/pkg/connector/catalog.go:42 +0x197
fybrik.io/fybrik/pkg/connectors/protobuf._DataCatalogService_GetDatasetInfo_Handler(0x1521060, 0xc00033a9a0, 0x189ce60, 0xc0004b5590, 0xc000526d20, 0x0, 0x189ce60, 0xc0004b5590, 0xc0003190c0, 0x1b)
	/home/runner/work/fybrik/fybrik/pkg/connectors/protobuf/data_catalog_service_grpc.pb.go:89 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000260a80, 0x18ac8b8, 0xc00028a600, 0xc000508a20, 0xc00044a660, 0x21a4a20, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000260a80, 0x18ac8b8, 0xc00028a600, 0xc000508a20, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000436d0, 0xc000260a80, 0x18ac8b8, 0xc00028a600, 0xc000508a20)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.39.0/server.go:938 +0x1fd

**Comment by shlomitk1** [comment]
This issue has been resolved in 0.6 - the pod is no longer crashing. Closing this issue.
