### ISSUE TITLE
Validate connectors requests/responses against taxonomy

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#1090]
Validate all requests/responses to connectors. Can probably be part of the client code in manager.

**Comment by rohithdv** [comment]
Hi @roee88 To validate asset request ( for example ) I will need to reference the schema file as below in the code. Can I do something like below ? Thanks. 
```
	taxonomyFile := "file://" + filepath.ToSlash("../../../charts/fybrik/files/taxonomy/datacatalog.json") + "#/definitions/GetAssetRequest"
	err = r.ValidateAssetRequest(&request, taxonomyFile)
	if err != nil {
		return err
	}
```

**Comment by shlomitk1** [comment]
@rohithdv Isn't this json file copied to /tmp/taxonomy directory of the manager pod?

**Comment by rohithdv** [comment]
Thanks @shlomitk1 !
