### ISSUE TITLE
Generate json schemas for validation from FybrikApplication and FybrikModule code

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#1091]
Looking at the flow for taxonomy validation of CRDs (e.g., FybrikApplication and [FybrikModule](https://github.com/fybrik/fybrik/pull/804)) I'm a bit worried about keeping consistency between the structure in the CRD and the structure in the validation object. The latter must be a subset of the former with `additionalProperties: true` set in the right places to allow the additional fields that don't require validation. Whenever the structure of the CRD would change we will need to be careful about the structure of the validation object. 

_Originally posted by @roee88 in https://github.com/fybrik/fybrik/discussions/848_

**Comment by roytman** [comment]
Hey @Mohammad-nassar10 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/fybrik-main-61d4121dc68e8800105072bb/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
