### ISSUE TITLE
Taxonomy instructions - broken links

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1112]
When following the [instructions](https://fybrik.io/v0.5/tasks/custom-taxonomy/#taxonomy-compile-cli-tool) for generating the taxonomy, the example base and layer taxonomies are dead links.
@roee88 @ronenkat

**Comment by roee88** [comment]
The dev docs have working links so 0.6 should be fine. 

Going forward it requires the same solution as https://github.com/fybrik/fybrik/issues/923, so you can definitely higher its priority but I don't think it's a blocker for 0.6.
