### ISSUE TITLE
External access not removed when modules namespace not default

### ISSUE THREAD

**Issue by laurieaw63** [fybrik/fybrik#1128]
The external data access module helm release is not being removed when specifying the modules namespace label,  The deleteExternalResources method is using the wrong namespace; should be blueprint.Spec.ModulesNamespace instead of blueprint.Namespace. Related to PR #990 for issue #793.

Need to avoid loading CRDs when running unit tests (suite_test.go) if using an existing controller.

PR being submitted shortly.....

**Comment by shlomitk1** [comment]
Please see https://github.com/fybrik/fybrik/pull/1118 that has resolved the first issue.

**Comment by shlomitk1** [comment]
implemented in https://github.com/fybrik/fybrik/pull/1135
