### ISSUE TITLE
Soft Policy Implementation

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1131]
- [x] Expand current pkg/adminconfig code to support the evaluation of soft policies and returning their results in addition to the hard policy decisions supported today.

- [x] Provide sample soft policies.

- [ ] Provide documentation for authoring soft policies.

- [x] Modify taxonomy accordingly

**Comment by shlomitk1** [comment]
Soft policies will be added in https://github.com/fybrik/fybrik/issues/1589. Closing this issue.
