### ISSUE TITLE
Explore Leveraging External Building Blocks as Modules

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1137]
Currently fybrik has a very limited number of services being used as FybrikModules.  It would benefit the fybrik community greatly if there was a larger library of capabilities that could be used in data planes generated by fybrik.  To this end, we want to explore if/how we can leverage building blocks from other products and open source products.

For example, building blocks used in ETL tools whether proprietary (ex: Data Stage) or open source , tekton pipeline building blocks, etc.

Tasks:
- [x] Identify relevant technologies who's building blocks would be candidates 
- [x] Determine what would be required to leverage them for use in fybrik.  Ex: Can we provide tools for generating the FybrikModule yaml? How do we deploy? etc
- [x] Demo showing how an external building block could be used in fybrik

**Comment by simanadler** [comment]
I did some very initial investigation into possible directions for reusable components, and these might be some places to start:
* Tekton catalog - https://github.com/tektoncd/catalog
* List of popular open source ETL tools - https://hevodata.com/learn/open-source-etl-tools-in-2021/
* Apache Camel component catalog - https://camel.apache.org/components/next/
* dbt - https://github.com/dbt-labs/dbt-core

**Comment by cdoron** [comment]
We would like to experiment with AirByte for this task.
Here is a list of AirByte Connectors: https://docs.airbyte.com/integrations
The list includes connectors for: CockroachDB, DB2, MongoDB, MySQL, Postgres, S3, and Snowflake.
Which, in your opinion, would be a good starting point for this experiment? @roytman, @simanadler, @roee88, @shlomitk1

**Comment by simanadler** [comment]
@cdoron See my thoughts below.  I personally would suggest starting with Google Sheets.
@roytman @flora177 @roee88 Your thoughts?

**Source** (read modules)

s3 (alpha) - it might be interesting to use in incremental sync mode.  Could possibly be incorporated into the demo we are working on.  

Google Sheets (certified) - Would be cool to show the quick start scenario with a read module that reads from Google Sheets

US Census (alpha) - This would be a cool new type of read module

CockroachDB, DB2, MongoDB, MySQL, Postgres, and Snowflake you suggested are all interesting too.

**Destination** (write modules)
We can look at this as a second step

**Comment by simanadler** [comment]
@flora177 Suggested the following: maybe add this (in low place as healthcare in not in IBM’s top now, but could be interesting)
 
https://github.com/Alvearie/keycloak-extensions-for-fhir

**Comment by simanadler** [comment]
Summary of findings: https://ibm.box.com/s/8x7oykzwuxtbdod3eeon4ek1e2a3i8ci
