### ISSUE TITLE
Multi-cluster sample case

### ISSUE THREAD

**Issue by pugangxa** [fybrik/fybrik#1201]
I just managed to run cases in the multi-cluster environment, the process is really painful, since there's multiple components needed and no document provided so I must read code and design my case carefully, and during that I encountered some code issues too. After all these things, the case I run is:
1: The control cluster and the remote cluster are in different region, the workload(notebook) located at control cluster requires to read data from remote cluster. After configuring correct storage account and policy,  an implicit copy module will be enabled in remote cluster besides a read module in control cluster.
2: Both the workload and asset are located at remote cluster, to enable read module need submit fybrik application to control cluster.

Better if we can provide document and sample for that.

**Comment by shlomitk1** [comment]
Can you detail the code issues you have encountered?

**Comment by pugangxa** [comment]
> Can you detail the code issues you have encountered?

Yes, in fact it all resolved and it works now. For the code issue we encountered, it's PR #1174 , PR #1197, PR #1118, PR #1104, PR #1072, PR #1053, PR #1153, PR #1136, PR #1110, PR #1081, PR  #1080 and https://github.com/fybrik/data-movement-operator/issues/27, https://github.com/fybrik/mover/issues/116. Besides we need design the case and policy and storage account carefully. I think it's really not easy to run such case, Better to have sample and document.

**Comment by pugangxa** [comment]
Discussed with team, we can contribute the configuration and steps since we just finished the case. Just not sure whether it fits to a sample or a unit test case. I think maybe as a sample is better because it relies on motion operator and mover components?

**Comment by shlomitk1** [comment]
> > Can you detail the code issues you have encountered?
> 
> Yes, in fact it all resolved and it works now. For the code issue we encountered, it's PR #1174 , PR #1197, PR #1118, PR #1104, PR #1072, PR #1053, PR #1153, PR #1136, PR #1110, PR #1081, PR #1080, [fybrik/data-movement-operator#28](https://github.com/fybrik/data-movement-operator/pull/28) and [fybrik/data-movement-operator#27](https://github.com/fybrik/data-movement-operator/issues/27), [fybrik/mover#116](https://github.com/fybrik/mover/issues/116). Besides we need design the case and policy and storage account carefully. I think it's really not easy to run such case, Better to have sample and document.

Yes, you are right. My question was to identify problems in the code that need to be addressed, and I'm glad to hear that all of them have been resolved :-)

**Comment by pugangxa** [comment]
To have some background, we just joined the m4d family recently so we decided to spend some time to run some cases to know this project better. This is really difficult but the good thing is now we think we are really familiar with the components here:) Thanks for all your help.

**Comment by ityuhui** [comment]
I'm pareparing a document to summary our experiment for the multicluster sample.
Hope to finish the draft soon...
