### ISSUE TITLE
Refine ModuleArguments structure

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1202]
Structure of module arguments is hard-coded and depends on the flow (read, copy, write). It should be easier to define.
Some thoughts:
- no read/copy/write: an optional list of source/sink/actions tuples
- provide additional information, such as workload properties, appInfo
- provide the selected capability, e.g. read, register_asset

**Comment by elsalant** [comment]
For HEIR, there is a requirement that the Module log (pass to Kafka) the application intent.  Currently, attributes under appInfo are not passed to the module
