### ISSUE TITLE
Support K8s 1.22 by Fybrik and all sub repositories

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1216]
The latest OpenShift 4.9 runs on Kubernetes 1.22. Fybrik should support this version.
in addition, we have to move to v1.17 of goLang

**Comment by revit13** [comment]
Datashim fails to work with k8s 1.22 here is an error from the log `kubectl logs csi-controller-h3-0 csi-attacher
`:
` 1 reflector.go:188] Listing and watching *v1beta1.VolumeAttachment from k8s.io/client-go/informers/factory.go:135
E0131 06:36:00.527901       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.VolumeAttachment: the server co`

It has an open issue for upgrading: https://github.com/datashim-io/datashim/issues/156

**Comment by srikumar003** [comment]
@revit13 @roytman It seems the error is coming from CSI-H3 connector which you do not need. You can look at the Helm chart (https://github.com/datashim-io/datashim/blob/master/chart/values.yaml) to only install csi-s3 (i.e. `--set csi-h3-chart.enabled="false"` to not install H3).

**Comment by revit13** [comment]
@srikumar003 Thanks! will check it out. btw regarding datashim chart - is it published or should I do `git clone` before the `helm install` command?

**Comment by roytman** [comment]
Done
