### ISSUE TITLE
Implement storage account selection

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1220]

**Comment by simanadler** [comment]
The decision may have to be made based on a combination of data governance and config policies.  For example, there could be a governance policy that says PII of Turkish residents cannot be written in the Netherlands, and a config policy that restricts to storage accounts <= $80

**Comment by shlomitk1** [comment]
> The decision may have to be made based on a combination of data governance and config policies. For example, there could be a governance policy that says PII of Turkish residents cannot be written in the Netherlands, and a config policy that restricts to storage accounts <= $80

Right. I referred to the config admin policies explicitly because their validation is missing, whereas governance restrictions are checked.
