### ISSUE TITLE
Add interface to register new asset in katalog (and egeria?)

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1230]

**Comment by rohithdv** [comment]
The following is enlisting of various scenarios for write flow. Please review. Thanks. @roytman @shlomitk1 @simanadler 

**Write Flows:**

The write request is specified by populating the `CreateAssetRequest` object and sending the object through the `createAssetInfo` Handler in the HTTP server (for eg: `katalog-connector`).

```
type CreateAssetRequest struct {
    // The destination catalog id in which the new asset will be created based on the information provided in ResourceMetadata and ResourceDetails field
    DestinationCatalogID string `json:"destinationCatalogID"`
    // +kubebuilder:validation:Optional
    // Asset ID to be used for the created asset
    DestinationAssetID string `json:"destinationAssetID,omitempty"`
    // Source asset metadata like asset name, owner, geography, etc
    ResourceMetadata ResourceMetadata `json:"resourceMetadata"`
    // Source asset details like connection and data format
    ResourceDetails ResourceDetails `json:"resourceDetails"`
    // +kubebuilder:validation:Optional
    // The vault plugin path where the destination data credentials will be stored as kubernetes secrets
    Credentials string `json:"credentials"`
}
```

There are different scenarios which result in different parameters which need to be passed in `CreateAssetRequest` object.

_Scenario 1:_ 
The following fields are given valid values in CreateAssetRequest from the `manager`:

> 	DestinationCatalogID
> 	DestinationAssetID
> 	ResourceMetadata
> 	ResourceDetails
> 	Credentials

_Algorithm_:
	The createAssetInfo implementation has the following pseudocode:
		1. Parse `CreateAssetRequest` object requires to get the input fields.
		2. Create an empty Asset object called createdAsset. (as defined in "[fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1](http://fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1)”)
		3. Populate createdAsset with relevant values extracted from `CreateAssetRequest` input object.
		4. Invoke the controller-runtime `Create` method to create the Asset in the cluster 
		5. Return 201 Created HTTP Code along with the newly created asset id (same as `DestinationAssetID`) 

_Scenario 2:_
The following fields are given valid values in CreateAssetRequest from the `manager`:

> 	DestinationCatalogID
> 	ResourceMetadata
> 	ResourceDetails
> 	Credentials

 
_Algorithm:_
	The createAssetInfo implementation has the following pseudocode:
		1. Parse `CreateAssetRequest` object requires to get the input fields.
		2. Create an empty Asset object called createdAsset (Based on definition in "[fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1](`http://fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1`)”)
		3. Since `DestinationAssetID` is not provided, use `ResourceMetadata.Name` + random string (of length 3) to generate the DestinationAssetID
		3. Populate createdAsset with relevant values extracted from `CreateAssetRequest` input object.
		4. Invoke the controller-runtime `Create` method to create the Asset in the cluster 
		5. Return 201 Created HTTP Code along with the newly created asset id (same as `DestinationAssetID`). Return Error if this operation fails. 

_Scenario 3:_
The following fields are given valid values in CreateAssetRequest from the `manager`:

> 	DestinationCatalogID
> 	ResourceMetadata (but ResourceMetadata.name is empty)
> 	ResourceDetails
> 	Credentials

 
_Algorithm:_
	The createAssetInfo implementation has the following pseudocode:
		1. Parse `CreateAssetRequest` object requires to get the input fields.
		2. Create an empty Asset object called createdAsset (Based on definition in "[fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1](http://fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1)”)
		3. Since `DestinationAssetID` and `ResourceMetadata.Name` is not provided, use random string (of length 8) to generate the `DestinationAssetID`
		3. Populate createdAsset with relevant values extracted from `CreateAssetRequest` input object.
		4. Invoke the controller-runtime `Create` method to create the Asset in the cluster 
		5. Return 201 Created HTTP Code along with the newly created asset id (same as `DestinationAssetID`). Return Error if this operation fails.

**Comment by shlomitk1** [comment]
@rohithdv Regarding Katalog, DestinationAssetID is the Asset resource name. Please note that it should be unique if DestinationAssetID is not provided, otherwise it may be an update of the existing one. DestinationCatalogID is the namespace where Asset is created. It is assumed to exist otherwise an error is returned (I think the assumption for all catalog managers is that we don't create a new catalog).

**Comment by simanadler** [comment]
> The following is enlisting of various scenarios for write flow. Please review. Thanks. @roytman @shlomitk1 @simanadler
> 
> **Write Flows:**
> 
> The write request is specified by populating the `CreateAssetRequest` object and sending the object through the `createAssetInfo` Handler in the HTTP server (for eg: `katalog-connector`).
> 
> ```
> type CreateAssetRequest struct {
>     // The destination catalog id in which the new asset will be created based on the information provided in ResourceMetadata and ResourceDetails field
>     DestinationCatalogID string `json:"destinationCatalogID"`
>     // +kubebuilder:validation:Optional
>     // Asset ID to be used for the created asset
>     DestinationAssetID string `json:"destinationAssetID,omitempty"`
>     // Source asset metadata like asset name, owner, geography, etc
>     ResourceMetadata ResourceMetadata `json:"resourceMetadata"`
>     // Source asset details like connection and data format
>     ResourceDetails ResourceDetails `json:"resourceDetails"`
>     // +kubebuilder:validation:Optional
>     // The vault plugin path where the destination data credentials will be stored as kubernetes secrets
>     Credentials string `json:"credentials"`
> }
> ```
> 
> There are different scenarios which result in different parameters which need to be passed in `CreateAssetRequest` object.
> 
> _Scenario 1:_ The following fields are given valid values in CreateAssetRequest from the `manager`:
> 
> > DestinationCatalogID
> > DestinationAssetID
> > ResourceMetadata
> > ResourceDetails
> > Credentials
> 
> _Algorithm_: The createAssetInfo implementation has the following pseudocode: 1. Parse `CreateAssetRequest` object requires to get the input fields. 2. Create an empty Asset object called createdAsset. (as defined in "[fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1](http://fybrik.io/fybrik/connectors/katalog/pkg/apis/katalog/v1alpha1)”) 3. Populate createdAsset with relevant values extracted from `CreateAssetRequest` input object. 4. Invoke the controller-runtime `Create` method to create the Asset in the cluster 5. Return 201 Created HTTP Code along with the newly created asset id (same as `DestinationAssetID`)


What happens if the asset already exists in the catalog?  I assume you will return a warning/error. Right?

**Comment by rohithdv** [comment]
> @rohithdv Regarding Katalog, DestinationAssetID is the Asset resource name. Please note that it should be unique if DestinationAssetID is not provided, otherwise it may be an update of the existing one. DestinationCatalogID is the namespace where Asset is created. It is assumed to exist otherwise an error is returned (I think the assumption for all catalog managers is that we don't create a new catalog).

@shlomitk1 @simanadler  I have updated the scenarios based on your queries. Please review. Specifically, please check Step 4 in the above algorithms. Thanks.

**Comment by roytman** [comment]
Are there any restrictions on the length of DestinationAssetID? 

- If not, why do you `random string (of length 3)` in scenario 2 and  `random string (of length 8)` in scenario 3?  The longer random string reduces conflict probability.  

- If yes, `ResourceMetadata.Name + random string (of length 3)` might create a violation in scenario 2.

**Comment by rohithdv** [comment]
I think the restriction on kubernetes resource names is [253 characters](https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/overview/working-with-objects/names/#:~:text=By%20convention%2C%20the%20names%20of,resources%20have%20more%20specific%20restrictions.). I have made random string length as 8 everywhere. Please suggest if I need to increase it. Thanks. @roytman

**Comment by shlomitk1** [comment]
Regarding this step in scenario 1.
4. Check for existence of DestinationAssetID in DestinationCatalogID. If it exists, then return Error.
- Is there a way to distinguish between different types of errors? It could be a real error (communication with the server has failed) or not (an asset exists, apply Update instead of Create).
