### ISSUE TITLE
Storage allocation - support data stores other than COS which is currently supported

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1240]

**Comment by shlomitk1** [comment]
@simanadler datashim supports various S3 data stores, not only COS. "cos" is just a name they use for s3 inside a dataset object.

**Comment by revit13** [comment]
the quick start uses localstack...

**Comment by revit13** [comment]
what about allocation in other storage types like google-sheet etc? I think it was raised before to consider the option that an external component will handle the allocation.
