### ISSUE TITLE
Update Hard Policy Result Approach

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1252]
Hard policies whose results include restrictions should return restrictions (ex: storagecost <= $80) rather than solutions (ex: a list of storageaccounts whose cost is <= $80).

A hard policy "solver function" should take  the hard policy evaluation results, and based on those and the infrastructure metadata values determine the solutions.

The reason for this separation it to ensure that the IT Admin writing the policies doesn't have to provide in the rego policies the logic for choosing the solution.  This is also more consistent with the approach that will be taken with soft policies and the (future) introduction of the optimizer.

**Comment by shlomitk1** [comment]
https://github.com/fybrik/fybrik/pull/1249 addresses this issue
