### ISSUE TITLE
Wrong CRD Spec definition as an optional field

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1285]
Some of Fybrik CRDs, e.g. `fybrikapplication` and  `plotter`, have the wrong definition Spec as an optional filed. 
see K8s [API reference](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/)
We can see it in the go Object, where the Spec has the `omitempty` tag, in its yaml file, and at the Web site reference. 
Please review all fybrik CRDs and fix it.

**Comment by shlomitk1** [comment]
Interesting, we used `kubebuilder create` to create most CRDs. Their tutorial has a resource with an optional Spec...

**Comment by roytman** [comment]
> Interesting, we used `kubebuilder create` to create most CRDs. Their tutorial has a resource with an optional Spec...

Does it make sense to create a `fybrikapplication` without Spec ?
