### ISSUE TITLE
Hardening pods security

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1310]
In order to harden pods security, the `SecurityContext` and `PodSecurityContext` should be defined.
Currently, they are empty.

**Comment by revit13** [comment]
@roytman I think there is an issue with SecurityContext  and openshift, for example see vault [deployment](https://github.com/hashicorp/vault-helm/blob/248397f663f5ceb1bf20ab287deb3fd246a3d593/templates/server-statefulset.yaml#L49)
