### ISSUE TITLE
Interface field in FybrikApplication is confusing

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1382]
We refer to the `interface` field inside dataset requirements in a different way based on the flow. Sometimes (read, write) it is an interface between the workload and the virtual module endpoint. Sometimes it is a desired protocol/format of a target, as in copy. It is especially confusing when coming to the write scenario where we have both interface between the workload and the module, and the written asset requirements (if exist). 
Proposal:  `interface` will define the interface between the workload and the module, while adding `target` structure to define requirements on a target (optionally), such as connection, format, metadata.

**Comment by roytman** [comment]
@shlomitk1, do you have any updates ?
