### ISSUE TITLE
Treat an empty data format as "any" while matching interface requirements

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1383]
Use-case: a delete flow. I'd assume a delete module supports some connections (e.g. s3) but not others, i.e. it can delete an asset from a bucket but not a table from a database. But then, it does not care about the data format of the asset to be deleted. 
Another use-case may be creating an asset while not indicating the required format (let Fybrik choose one of the formats supported by the deployed write module). We'd like to have format matching pass in these cases (i.e. comparing a format with an empty string).

**Comment by revit13** [comment]
@simanadler IIUC the user writes datasets from his notebook, so he does not need to know the dataset's format in which it will be saved in the bucket. This is also true for reading the data afterward.

**Comment by shlomitk1** [comment]
Implemented in https://github.com/fybrik/fybrik/pull/1408
