### ISSUE TITLE
Fybrik Errors when it deployed with clusterScoped: false

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1384]
When we deploy fybrik and `clusterScoped` is `false` we got the following errors:

- [ ]  helm install fybrik ... returned "Error: INSTALLATION FAILED: namespaces "fybrik-blueprints" not found". Can be resolved by commenting out the cluster scope restrictions in `fybrik-blueprints-ns.yaml` 
- [ ] After successful installation, we observed the following errors in the manager log:

> E0327 08:15:50.963142       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.FybrikApplication: failed to list *v1alpha1.FybrikApplication: fybrikapplications.app.fybrik.io is forbidden: User "system:serviceaccount:fybrik-system:manager" cannot list resource "fybrikapplications" in API group "app.fybrik.io" at the cluster scope

> E0327 07:41:06.876241       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:167: Failed to watch *v1alpha1.FybrikApplication: failed to list *v1alpha1.FybrikApplication: fybrikapplications.app.fybrik.io is forbidden: User "system:serviceaccount:fybrik-system:manager" cannot list resource "fybrikapplications" in API group "app.fybrik.io" at the cluster scope
2022-03-27T07:41:06.923Z	ERROR	controller-runtime.manager.controller.blueprint	Could not wait for Cache to sync	{"reconciler group": "app.fybrik.io", "reconciler kind": "Blueprint", "error": "failed to wait for blueprint caches to sync: timed out waiting for cache to be synced"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:195
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:221
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1

**Comment by roytman** [comment]
OK, I fixed it by defining `.Values.applicationNamespace`. 
But we have here asymmetry between ClusterScope and Namespace scopes.
When we define `clusterScope: true`: 

- we don't have to create `fybrik-blueprints` (.Values.modulesNamespace) in advice.
-  we don't have to explicitly define `.Values.applicationNamespace` and it is set by default to value of `Values.modulesNamespace` (fybrik-blueprints)

The namespace should be created and defined, when we work with `clusterScope: false`

**Comment by shlomitk1** [comment]
For clusterScope = true, we still need to create fybrik-blueprints (or similar) namespace.
applicationNamespace is not relevant for cluster-scoped deployment.

**Comment by roytman** [comment]
no `fybrik-blueprints ` is created automatically, see https://github.com/fybrik/fybrik/blob/15fab6b60f25c00ce27947277b3cab4e08d9f860/charts/fybrik/templates/fybrik-blueprints-ns.yaml#L2

**Comment by shlomitk1** [comment]
I think the "if" statement is not required, as the namespace is created for both cases.

**Comment by roytman** [comment]
> I think the "if" statement is not required, as the namespace is created for both cases.

exactly, it was my comment at the first bullet . "Can be resolved by commenting out the cluster scope restrictions in fybrik-blueprints-ns.yaml"

**Comment by roytman** [comment]
OK, we don't want to delegate to Fybrik management of user namespaces, so these namespaces should be created before Fybrik deployment and are not deleted when Fybrik is uninstalled.
