### ISSUE TITLE
Different log formats of the Fybrik manager

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1399]
- The Fybrik log file contains outputs with at least 2 different formats: 
```
2022-03-31T08:02:54.666Z	INFO	controller-runtime.webhook	serving webhook server	{"host": "", "port": 9443}
```
and 
```
{"level":"trace","Controller":"Blueprint","time":"2022-03-31T08:02:54Z","caller":"/home/runner/work/fybrik/fybrik/manager/controllers/app/blueprint_controller.go:429","message":"Concurrent blueprint reconciles: 1"}
```

- The "caller" field of the Fybrik logger always contains the same information, see above. We have to either find a way to print the caller info from the last-1 stacktrace (the better option), or remove this field.  

CC: @simanadler

**Comment by shlomitk1** [comment]
("sigs.k8s.io/controller-runtime").Manager uses `Logger logr.Logger` while Fybrik uses zerolog.Logger that does not implement the same interface, thus can not be passed to controller-runtime.Manager.
Perhaps the solution could be to create a wrapper over zerolog.Logger that will implement logr.Logger interface.

**Comment by simanadler** [comment]
@shlomitk1 is correct.  The first log entry you listed was not generated by fybrik.  Not sure if we need to invest in trying to align them.

Not sure what you mean regarding the second item.  The caller contains the file and row # that generated the log.  It's not the same all the time.

**Comment by shlomitk1** [comment]
Reopening, will be needed for log analysis
