### ISSUE TITLE
Timing issue when removing an asset from fybrikapplication right before deleting the fybrikapplication

### ISSUE THREAD

**Issue by jlkaus** [fybrik/fybrik#1410]
In my testing of creating and using a fybrikapplication, then removing it and doing it again, I found I was hitting a timing window when removing the asset from the fybrikapplication, then deleting the fybrikapplication.  Some sort of timing window during reconcilation, where the reconcilation of removing the asset may not have completed by the time the fybrikapplication is removed, causing the finalizer for the fybrikapplication to get stuck, and leaving the fybrikapplication CR around in kubernetes.  Sometimes the associated plotter/blueprint/module helm install and associated objects are also left behind, but usually they go away fine.

This doesn't happen every time.  In running ~1000 times, it maybe happened around 10-20 times, where I would be left with all these old fybrikapplications that weren't able to finalize the deletion.  Manually removing the finalizer from the application works, or, in the cases where blueprints/plotters/helm installs were left behind, manually deleting those objects helps too.

By adding a 5 second delay in my test script, after removing the asset from the application, and before deleting the fybrikapplication, this problem went away completely, and everything always cleaned up entirely fine.  (Note that while I originally though this might be related to issue #1409, with my 5 second delay added here, #1409 still occurs, so they don't appear related).

This also doesn't happen if you don't bother removing the asset before deleting the fybrikapplication.  In that case, deleting the fybrikapplication causes everything else to clean up fine, and finalization occurs fine as well.  But ideally we should be able to remove the asset first, and the fybrikapplication deletion should be able to fully clean up, even if the asset removal is in progress at that point.

In the manager pod logs, I see these errors when this happens:

```
{"level":"trace","Controller":"FybrikApplication","fybrikapplication":"fybrik-jlkaus/fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c","app.fybrik.io/app-uuid":"15b03e59-8328-49e2-ad03-43ad1223e714","Action":"Delete","time":"2022-04-05T19:04:54Z","caller":"/workspace/source/mesh-for-data/manager/controllers/app/fybrikapplication_controller.go:293","message":"Reconcile: FybrikApplication is deleting the generated Plotter"}
2022-04-05T19:04:54.332Z        ERROR   controller-runtime.manager.controller.fybrikapplication Reconciler error        {"reconciler group": "app.fybrik.io", "reconciler kind": "FybrikApplication", "name": "fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c", "namespace": "fybrik-jlkaus", "error": "plotters.app.fybrik.io \"fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c-fybrik-jlkaus\" not found"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Projects/Proj1/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /Projects/Proj1/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
```

Prior to that, I see messages about deleting the plotter, also hitting an error about the fybrikapplication having been updated in the meantime (probably the deletion of the fybrikapplication?)
```
{"level":"trace","Controller":"FybrikApplication","fybrikapplication":"fybrik-jlkaus/fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c","app.fybrik.io/app-uuid":"15b03e59-8328-49e2-ad03-43ad1223e714","Action":"Delete","time":"2022-04-05T19:04:53Z","caller":"/workspace/source/mesh-for-data/manager/controllers/app/fybrikapplication_controller.go:293","message":"Reconcile: FybrikApplication is deleting the generated Plotter"}
{"level":"info","Controller":"FybrikApplication","fybrikapplication":"fybrik-jlkaus/fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c","app.fybrik.io/app-uuid":"15b03e59-8328-49e2-ad03-43ad1223e714","time":"2022-04-05T19:04:54Z","caller":"/workspace/source/mesh-for-data/manager/controllers/app/fybrikapplication_controller.go:345","message":"No plotter will be generated since no datasets are specified"}
{"level":"trace","Controller":"FybrikApplication","fybrikapplication":"fybrik-jlkaus/fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c","app.fybrik.io/app-uuid":"15b03e59-8328-49e2-ad03-43ad1223e714","Action":"Update","time":"2022-04-05T19:04:54Z","caller":"/workspace/source/mesh-for-data/manager/controllers/app/fybrikapplication_controller.go:160","message":"Updating status for desired generation 4"}
{"level":"trace","Controller":"FybrikApplication","fybrikapplication":"fybrik-jlkaus/fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c","time":"2022-04-05T19:04:54Z","caller":"/workspace/source/mesh-for-data/manager/controllers/app/fybrikapplication_controller.go:82","message":"*** FybrikApplication Reconcile ***"}
2022-04-05T19:04:54.110Z        ERROR   controller-runtime.manager.controller.fybrikapplication Reconciler error        {"reconciler group": "app.fybrik.io", "reconciler kind": "FybrikApplication", "name": "fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c", "namespace": "fybrik-jlkaus", "error": "Operation cannot be fulfilled on fybrikapplications.app.fybrik.io \"fybrik-1d99fba5-c82c-4aeb-b86f-658b7e0c023c\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /Projects/Proj1/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /Projects/Proj1/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
```

Another run is ongoing right now, and so far, out of 238 iterations, this has happened 3 times, leaving the applications behind in a deleted, but unable to finalize state.  So far, the blueprints/plotters/helm installs have always gone away ok, during these runs.

These runs were against the 0.6.3 code, I believe.

**Comment by roytman** [comment]
1. According to the first log snippet - when Fybrik objects delete generated objects during  finalization processing and K8s DELETE call returns "not found" the error should not be propagated to the upstream.
2. For the second one, we have to cherry-pick #1385

**Comment by jlkaus** [comment]
For reference, from my 1000 runs last night, this happened 26 times.
