### ISSUE TITLE
Revert #1285

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1412]
Some of our customers first create `fybricapplication` and only after that add assets to it. We have to allow it, so we need to revert #1285

**Comment by simanadler** [comment]
@roytman Question is whether the spec should be empty, or whether it's sufficient for the list of data assets in the spec to be empty

**Comment by roytman** [comment]
@shlomitk1 , where is an explanation of how `we` are allowing creation applications with no assets

**Comment by roytman** [comment]
false alarm
