### ISSUE TITLE
When Fybric runs with `clusterScope: true` it dosn't allow creation fybric applications with empty spec

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1413]
Following #1412, we are able to create fybricapplications with empty spec when `clusterScope: false`, but get the following error when it is `true`.
The FybrikApplication "my-notebook" is invalid: (root): Invalid value: map[string]interface {}{"appInfo":interface {}(nil), "data":interface {}(nil), "selector":map[string]interface {}{"clusterName":"", "workloadSelector":map[string]interface {}{}}}: spec is required.

**Comment by shlomitk1** [comment]
How would the cluster scope affect the validation of FybrikApplications? Perhaps, it does not create webhooks, so the apps are "created" but their status is marked as invalid. The proper way to create an app without any assets is to create an app with a spec including workload selector, creds and appInfo, but with an empty data array. In this case it's a valid application, and a "ready" status is returned.

**Comment by roytman** [comment]
the wrong definition of fybricApplication spec, its documentation will be updated.
