### ISSUE TITLE
Misconfigured Security Context for a Pod or Container

### ISSUE THREAD

**Issue by lxlcui** [fybrik/fybrik#1482]
@roytman

## Description
A security context defines privilege and access control settings for a Pod or Container. Security context settings includes:

**- Privileged** - To run privileged or unprivileged containers. Defaults to false.
**- RunasUser** - The uid to run the entry point of container process. If unspecified, defaults to user specified in the image metadata. This should be set to value greater than 10000.
**- RunAsNonRoot** - To ensure your container should not run as root. If unspecified or false, defaults to false, kubelet will not validate the image at runtime. This should be set to True.
**- readOnlyRootFilesystem** - To ensure containers root filesystem is read-only. If unspecified, defaults to false. This should be set to True.
**- AllowPrivilegeEscalation** - To ensure a process can’t gain more privileges that its parent process. If unspecified, defaults to true. This should be set to False
**- Linux Capabilities** - To ensure process get least privileges not all privileges of the root user. Defaults to the default set of capabilities granted by the container runtime. Drop All capabilities first and add the required ones.
**- Seccomp Profile** - To filter processes system calls. If unspecified, no seccomp profile will be applied by default. A seccomp profile should be enabled by specifying it.
**- Apparmor/SeLinux** - To enable mandatory access controls. If unspecified, the container runtime will allocate a random SeLinux context for each container.

**Please see below link for the comprehensive list:**

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#securitycontext-v1-core

During pentest, below security context fields misconfiguration were observed :

1. readOnlyRootFilesystem - It was set to nil/false for all the pods

2. Missing Drop-ALL option under securityContext - **fybrik-operator-manager**

5. RunasUser - all containers are running with UID value below 10000 

6. Apparmor/SeLinux - Not set for all pods

## Please refer below screenshot:

<img width="1138" alt="截屏2022-05-13 15 49 09" src="https://user-images.githubusercontent.com/30468198/168236905-4809e58e-67f6-4468-a312-16fad10c642e.png">

## Affected Container/Pod(s)
```
fybrik-manager 
fybrik-operator-manager 
```

## Risk Assessment
Setting Security Context has the greatest impact on reducing the attack surface.

## Fix Recommendation
Setallsecuritycontext fieldsforthecontainer/podtoreducetheattacksurface. 
References:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by revit13** [comment]
Regarding `readOnlyRootFilesystem`: it must be set to `false` for the manager to allow deployment of helm chart modules which involves pulling the chart to a local directory:

` Message:  An error was received for asset fybrik-notebook-sample/data-csv . If the error persists, please contact an operator.Error description: ChartDeploymentFailure: : ghcr.io/fybrik/arrow-flight-module-chart:0.0.0-master: failed to create temporary directory for chart pull: mkdir /tmp/fybrik-helm-971613924: read-only file system`

**Comment by shlomitk1** [comment]
> Regarding `readOnlyRootFilesystem`: it should be set to `false` for the manager to allow deployment of helm chart modules which involves pulling the chart to a local directory:
> 
> ` Message: An error was received for asset fybrik-notebook-sample/data-csv . If the error persists, please contact an operator.Error description: ChartDeploymentFailure: : ghcr.io/fybrik/arrow-flight-module-chart:0.0.0-master: failed to create temporary directory for chart pull: mkdir /tmp/fybrik-helm-971613924: read-only file system`

Also, when a solver is deployed, manager creates some temporary files in /tmp directory.
Can we perhaps set the root directory to some value other than /tmp, leaving /tmp to be read-write?

**Comment by roytman** [comment]
> Can we perhaps set the root directory to some value other than /tmp, leaving /tmp to be read-write?

we can do it by defining/tmp as a volume.

```yaml
volumeMounts:
- mountPath: /tmp
  name: tmp
```
```yaml
volumes:
- emptyDir: {}
  name: tmp
```
