### ISSUE TITLE
Insecure Communication

### ISSUE THREAD

**Issue by lxlcui** [fybrik/fybrik#1486]
@roytman

## Description
If requests are sent without SSL/TLS implementation, then all the communication data will be sent in clear text on the network. Any user in shared network can sniff these data and get sensitive information like authentication credentials, session details, personal data, etc.

## Reference:
https://www.cvedetails.com/cwe-details/319/Cleartext-Transmission-of-Sensitive-Information.html 
https://cassandra.apache.org/doc/latest/operating/security.html 
https://www.ibm.com/docs/en/b2b-integrator/6.1.0?topic=mailbox-securing-apache-zookeeper-ssl-connections
https://www.postgresql.org/docs/9.5/ssl-tcp.html 
https://www.golinuxcloud.com/configure-openldap-with-tls-certificates/

## Please refer below screenshots:

<img width="814" alt="截屏2022-05-13 16 25 58" src="https://user-images.githubusercontent.com/30468198/168243583-e81b364f-c897-43cb-87c0-f65aa46b5219.png">

## Affected Container/Pod(s)
```
fybrik-manager 
fybrik-operator-manager 
```

## Risk Assessment
An adversary can obtain a lot of sensitive information by sniffing traffic.

## Fix Recommendation
Require SSL/TLS for all sensitive pages. Non-SSL requests to these pages should be redirected to the SSL page. Set the secure flag on all sensitive cookies. Configure your SSL provider to only support strong algorithms. Ensure your certificate is valid, not expired, not revoked, and matches all domains used by the site.

**Comment by revit13** [comment]
@lxlcui istio enables Mutual TLS in the control plane components as noted in fybrik site: https://fybrik.io/v0.6/tasks/control-plane-security/. Such that one can choose to deploy it along fybrik. Is this a good solution for you?

**Comment by roytman** [comment]
@lxlcui, we are going to support TLS communication between the manager and all connectors, see
#1668 / #1671 , #1556, #1602, #1628, #1631,

**Comment by roytman** [comment]
Finally fixed by #1637
