### ISSUE TITLE
RunAsUser must be set to higher UID values i.e., greater than 10000

### ISSUE THREAD

**Issue by lxlcui** [fybrik/fybrik#1490]
@roytman

## Description
During active reconnaissance, it was observed that many containers are running with UID value below 10000. Container UID should be set to a high value(> 10000) to avoid conflicts with processes running on the host system.

## Reference: 
  http://www.lib4dev.in/info/hexops/dockerfile/301241284

## Related screenshots are shown below:
<img width="734" alt="截屏2022-05-13 17 24 45" src="https://user-images.githubusercontent.com/30468198/168254453-d6558275-ec8c-4d53-8fd8-e6810357aa7e.png">

<img width="789" alt="截屏2022-05-13 17 25 01" src="https://user-images.githubusercontent.com/30468198/168254470-25d9a749-49d4-4143-9635-eadbf2771bb8.png">

## Affected Container/Pod(s)
```
fybrik-manager 
fybrik-operator-manager 
```

## Risk Assessment
User UID can create conflicts with the hosts user table and processes running on the host system.

## Fix Recommendation
Ensure containers run with a high UID(> 10000) to avoid host conflict.

**Comment by roytman** [comment]
Will be resolved as part of https://github.com/fybrik/fybrik/issues/1482 solution
