### ISSUE TITLE
Problems with the solver on Mac

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1525]
The #1497 added google `or-tools` (fzn-or-tools) to Fybrik.  There are several issues with it:

[ ] the `hack/tools/install_or_tools.sh` installs it into the hack/tools/bin based on the host OS (Linux or MacOS) but after that the binary are [copied](https://github.com/fybrik/fybrik/blob/a7fa6eee7c3e452ca5f681ad13cd08c9315f23ee/pkg/optimizer/Makefile#L17) into the RHEL Docker.  I doubt that Mac version will run there.
[ ] the  `hack/tools/install_or_tools.sh`  has a bug for MacOS - the downloaded file is or-tools`__`flatzinc_MacOsX-12.2.1_v9.2.9972.tar.gz, which is not exist.
[ ] Finally, meantime, `or-tools` doesn't support MacOS with apple CPU. it's targeted to the next release only, or there are attempts (not always successful) [to compile it]( https://github.com/google/or-tools/issues/2332.).  Therefore, I cannot run `make install-tools` on my laptop. 

Can it be part of a docker  only?

**Comment by shlomitk1** [comment]
It can't be a part of a docker only, as it is tested mainly in the unit tests (running binary).
We still need to run the binary in CI.
I think we need:
1. not to create local Docker images for each test run but rather use the global image `ghcr.io/fybrik/optimizer:master` 
2. not to install or-tools for specific platforms
3. Empty CSP_PATH if the solver is not installed in (1)

**Comment by roytman** [comment]
I know that it is part of the manual tests, but it can be integrated into a docker similar as we run openapi generator. https://github.com/fybrik/fybrik/blob/a7fa6eee7c3e452ca5f681ad13cd08c9315f23ee/site/Makefile#L25

**Comment by shlomitk1** [comment]
> I know that it is part of the manual tests, but it can be integrated into a docker similar as we run openapi generator.
> 
> https://github.com/fybrik/fybrik/blob/a7fa6eee7c3e452ca5f681ad13cd08c9315f23ee/site/Makefile#L25

Not sure I understand. Do you suggest to run `go test` for the manager inside a container?

**Comment by roytman** [comment]
if possible, yes

**Comment by shlomitk1** [comment]
@roytman We are not testing the solver but rather the model creation/data path translation that is done by the manager. Manager assumes that the solver is present in its local file system. So what you suggest is actually to imitate the operation of CI that installs tools and runs manager tests inside the container. I don't see any benefits of doing this in addition to CI. It would be much easier to disable solver installation/run by not setting CSP_PATH for specific operation systems.

**Comment by roytman** [comment]
yes, but it will prevent testing "on specific operation systems", but we can leave with it for a while

**Comment by roytman** [comment]
@zivnevo, any progress with at least the first 2 bullets?

**Comment by zivnevo** [comment]
@roytman , can you please check if PR #1840 makes things better?
It's still not ready to be merged because of a failing test, but I would like to know if this works on your mac.

**Comment by roytman** [comment]
Hi @zivnevo , wow, with #1840 the things look much better. I was able to download the tared files and to run `./bin/fzn-or-tools  --helpfull`. 

How can I validate real work of solver?

P.S. #1840 probably resolves #1692 too, but it should be checked by @simanadler (she has MacOS with amd64)

**Comment by zivnevo** [comment]
@roytman , running `make test` will also test producing blueprints using the solver.

**Comment by roytman** [comment]
the `make test` passed. 
The next step will be to create images on Mac and deploy them.

**Comment by zivnevo** [comment]
PR #1840 is now merged.

**Comment by roytman** [comment]
The PR https://github.com/fybrik/fybrik/pull/1840, resolved most of the mentioned issues. 

In general, we should not use MACs to build images.
Closing the issue as resolved.
