### ISSUE TITLE
Missing the mkdocs  tool

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1529]
the tools.mk doesn't install `mkdocs`

plus a dependency module is missing 

> Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')
  in "/Users/alexey/goWork/src/github.com/fybrik/fybrik/site/mkdocs.yml", line 94, column 20
  
  https://github.com/facelessuser/pymdown-extensions/issues/110

> ERROR    -  Config value: 'plugins'. Error: The "macros" plugin is not installed
Aborted with 1 Configuration Errors!

**Comment by shlomitk1** [comment]
`pip install mkdocs-macros-plugin` solves the plugin issue.

**Comment by roytman** [comment]
@shlomitk1 I know how to resolve the the missing deployments, the issue is to update the tools.mk

**Comment by revit13** [comment]
btw https://github.com/fybrik/fybrik/tree/master/site contains the Requirements for generating the site and also should be updated if needed.
