### ISSUE TITLE
Provide a better report of non-fatal errors to users

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#153]
The goal of this issue is to improve reporting and management of non-fatal errors:
- When encountering too frequent retries, change the base in the exponential backoff to a higher value like 1s.
- Add a boolean flag to Error condition to indicate whether re-attempts will be done to fix the error.
Affects: FybrikApplication

**Comment by roytman** [comment]
@shlomitk1, what's the status of the issue? can it be closed?
