### ISSUE TITLE
Provide a better syntax for attribute definitions

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1536]
Currently, for each attribute we need to fill in some common details such as type, units, scale. 
Need to define common details once and include a reference to them in the attribute definition.

**Comment by zivnevo** [comment]
Looks good. Maybe also provide an example of how "bandwidth-like" attributes look like (e.g., what will be the `object` field in their definitions)

**Comment by simanadler** [comment]
@shlomitk1 Any reason not to put the definitions in the infrastructure taxonomy?

**Comment by shlomitk1** [comment]
> @shlomitk1 Any reason not to put the definitions in the infrastructure taxonomy?

It will be defined in the same taxonomy, with different keys.
