### ISSUE TITLE
Implement OpenMetadata catalog connector

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1593]
Implement: 

- [x] GetAssetInfo
- [x] CreateAsset
- [x] DeleteAsset
- [x] UpdateAsset

**Comment by cdoron** [comment]
- Wrote connector code, which uses auto-generated server code (from Fybrik catalog connector YAML) and auto-generated client code for OM.
- Added test based on mock OM server
- Read Tag Categories, Tags, and Table Custom Properties from a YAML file
