### ISSUE TITLE
Create demos based on OpenMetadata catalog

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1594]

**Comment by cdoron** [comment]
The following PRs updated the Fybrik documentation to replace `katalog` with `OpenMetadata`:

- https://github.com/fybrik/fybrik/pull/1721
- https://github.com/fybrik/fybrik/pull/1781
- https://github.com/fybrik/fybrik/pull/1798
- https://github.com/fybrik/fybrik/pull/1802
- https://github.com/fybrik/fybrik/pull/1806
-

**Comment by cdoron** [comment]
addressed by https://github.com/fybrik/kfp-components
