### ISSUE TITLE
Update Fybrik Web site with explanation about Openmetadata catalog

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1595]
- Instructions on how to deploy and integrate
- Package for easy deployment
- Change getting started examples to use it
- Samples

**Comment by cdoron** [comment]
The following PRs updated the Fybrik documentation to replace `katalog` with `OpenMetadata`:

- https://github.com/fybrik/fybrik/pull/1721
- https://github.com/fybrik/fybrik/pull/1781
- https://github.com/fybrik/fybrik/pull/1798
- https://github.com/fybrik/fybrik/pull/1802
- https://github.com/fybrik/fybrik/pull/1806
