### ISSUE TITLE
Migrate Ginkgo to v2

### ISSUE THREAD

**Issue by ityuhui** [fybrik/fybrik#1604]
Kubnernetes community requires all sig projects to migrate Ginkgo to v2 since Ginkgo v1 is deprecated.
(https://groups.google.com/a/kubernetes.io/g/dev/c/JyPme_98tL4/m/ujWYLRXsAwAJ?utm_medium=email&utm_source=footer)

Fybirk preferably migrates this library as well.

I am willing to take this task since I have some experience in https://github.com/fybrik/fybrik/issues/1257

**Comment by roytman** [comment]
Hi, @ityuhui , we are going to close v1.0 release, can you finish this issue ?

**Comment by ityuhui** [comment]
I'll try to do this work today.

If there are any risks that cannot be resolved quickly, I'll raise them here by the end of today.
