### ISSUE TITLE
create katalog asset: non-specific error returned

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1609]
When creating a new katalog asset (ex: via the write flow), if the asset name is not legal (ex: contains _) an "internal server error" is returned via the fybrikapplication.status.  The details of the error are available, but not propagated back to the user.

In the katalog connector logs one can see the error such as: 
Asset.katalog.fybrik.io "test_house_prices_submission-q4z7g" is invalid: [metadata.generateName: Invalid value: "test_house_prices_submission-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "test_house_prices_submission-q4z7g": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')] Connector=katalog-connector

**Comment by shlomitk1** [comment]
Fixed.
