### ISSUE TITLE
Installer of Fybrik env

### ISSUE THREAD

**Issue by flora177** [fybrik/fybrik#1618]
Simple script to install all needed pre-req components for running Fybrik.
What modules to include? 
Allow user to choose the modules, but include 2 default modules (ArrowFlight, AirByte)

- [ ] Add another script to cleanup the installation 

Estimated end date for option 1 and 2 (with samples) - Sun 24/07

**Comment by flora177** [comment]
Decided to write 2 installers (on local stack):

1. Installs till module level w/o samples - This enables the user to test his own module 
The user can decide on ArrowFlight module or Airbyte module
2. installs all including ArrowFlight Read and write sample (from quick start)

Assumption: The user does not have 
The script installs helm. kind, K8s if it is not installed (What version?) in a separate lib (not to harm the global installation).

**Comment by roytman** [comment]
the samples do not need K8s, just `kubectl` and I don't think we need to install the dependencies. We can check that they are exsist and if not, return an error message.

**Comment by roytman** [comment]
and maybe an additional option - to use a real K8s cluster instead of `kind`

**Comment by Raviv-S** [comment]
Yea, we meant only for `kubectl` to be installed.
I'll add an option for existing cluster, how and where do you suggest to test it?

**Comment by roytman** [comment]
let's talk about it later
