### ISSUE TITLE
new release creation doesn't update release in the fybrik-crd files 

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1625]
The annotation `controller-gen.kubebuilder.io/version` is not updated

**Comment by shlomitk1** [comment]
@roytman This has nothing to do with Fybrik release. The version here is the version of controller-gen:
> controller-gen --version
> Version: v0.7.0

**Comment by roytman** [comment]
@shlomitk1 we need automatically update the values when we create a new release. It can be rerun controller-gen, or just manually update the values.
We should prevent the situation when like now we have v1.0, but the BU just copied our repo have v0.7

**Comment by roytman** [comment]
wrong issue
