### ISSUE TITLE
Add to the RELEASE.md file instructions hot to run integration tests on an OpenShift cluster

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1634]
We've faced with a situation when our integration tests successfully finished on a kind cluster, but failed on an Openshift cluster.

Before publishing a release we have to run the integration tests on an OpenShift cluster and probably on an IKS cluster too.

**Comment by revit13** [comment]
integration tests target create a kind cluster and pushes the docker images to a local registry created. should this step be changed when running in openshift?

**Comment by shlomitk1** [comment]
If there is an existing cluster with Fybrik environment, the integration tests will fail because they assume a mockup environment.

**Comment by shlomitk1** [comment]
@roytman The problem is not running on an OS cluster. The same config + test would fail on kind as well.
