### ISSUE TITLE
Remove `replace` directive in go.mod

### ISSUE THREAD

**Issue by ityuhui** [fybrik/fybrik#1640]
`Helm` has bumped `containerd` to v1.6.6 https://github.com/helm/helm/pull/11093, this is a safe version.
`runc` is also upgraded due to the indirect dependency of `containerd`

So after Fybirk bumps Helm to v3.9.1 and above in the future, `replace` will not be needed in go.mod.

https://github.com/fybrik/fybrik/blob/f0dc75ebe926e1466196f487770d5ac6cdca0f0e/go.mod#L243-L246

**Comment by roytman** [comment]
Wow, cool, good news. Thanks
