### ISSUE TITLE
Error parsing PRETTY_LOGGING when manager is started from a command line 

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1643]
When manager is started from a command line, it prints the following error:

```
==> bin/manager -enable-application-controller                      
Trouble reading verbosity. Found . Using trace as default
Error parsing PRETTY_LOGGING
``` 

manager --help doesn't provide option to set `PRETTY_LOGGING`

**Comment by simanadler** [comment]
The manager reads the log verbosity from an environment variable.  This was done to enable all of the components in the fybrik control plane to read from the same place to set verbosity
