### ISSUE TITLE
Multi-cluster setup: unregister a cluster does not work

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1656]
Trying to unregister a cluster, a namespace razeedeploy is not deleted, causing the unregistered cluster to re-appear as registered.
Where should this issue be submitted?

**Comment by roytman** [comment]
@shlomitk1, does it happen with Satellite too?, if yes we can ask support from the Satellite team

**Comment by shlomitk1** [comment]
Yes, IBM Satellite

**Comment by shlomitk1** [comment]
Steps to reproduce:
1. Register a cluster - a namespace razeedeploy is created.
2. Cluster becomes Active
3. Unregister the cluster. Cluster disappears from the view but re-appears after several seconds.
The only way to unregister the cluster is to delete razeedeploy namespace manually.

**Comment by roytman** [comment]
I have some issues with my VPN, so I cannot validate it, but before unregister the cluster, did you run the `Satellite Config removal job` ?

`oc apply -f https://raw.githubusercontent.com/IBM-Cloud/kube-samples/master/satellite/satconfig/satconfig_remove.yaml` 

see https://cloud.ibm.com/docs/satellite?topic=satellite-remove-satconfig
