### ISSUE TITLE
Functions in pkg/vault are not used.

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#1658]
It seems that the functions for vault functionality are not used and might be removed.

// Interface provides vault functionality
type Interface interface {
	LinkPolicyToIdentity(identity string, policyName string, boundedNamespace string, serviceAccount string, auth string, ttl string) error
	RemovePolicyFromIdentity(identity string, policyName string, auth string) error
	WritePolicy(policyName string, policy string) error
	DeletePolicy(policyName string) error
	Mount(path string) error
	DeleteSecret(vaultPath string) error
	GetSecret(vaultPath string) (string, error)
	AddSecret(path string, credentials map[string]interface{}) error
	AddSecretFromStruct(path string, creds interface{}) error
}

**Comment by shlomitk1** [comment]
The intention was to configure vault policies dynamically in the manager code rather than running a script. Did we abandon this idea completely? 
@simanadler FYI

**Comment by revit13** [comment]
OK for that reason it makes sense to leave it.

**Comment by simanadler** [comment]
When I wrote the vault stuff many moons ago these functions were being used.  Are we no longer storing the credentials for datasets in vault and passing them to the modules?
