### ISSUE TITLE
Define versioning of IT config policies

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1678]
Please update or continue https://github.com/fybrik/fybrik/pull/1670
And define a backward compatibility mechanism.

**Comment by shlomitk1** [comment]
IT policy structure is a part of Fybrik release, it's the same version.

**Comment by roytman** [comment]
@shlomitk1 , indeed IT policy structure is part of Fybrik, but the policies are an external part. What can be done (or what should be avoided) in order to support compatibility between releases?  The scenario is we deploy Fybrik version X  and IT admin defined IT policies, now we upgrade Fybrik deployment to version X+1. Will the old IT policies work?

**Comment by shlomitk1** [comment]
> @shlomitk1 , indeed IT policy structure is part of Fybrik, but the policies are an external part. What can be done (or what should be avoided) in order to support compatibility between releases? The scenario is we deploy Fybrik version X and IT admin defined IT policies, now we upgrade Fybrik deployment to version X+1. Will the old IT policies work?

If there are no changes to policy structure, the old policies will work. We have tests that will fail if backward compatibility is violated.

**Comment by shlomitk1** [comment]
Version of IT config policies is a version of Fybrik. We have tests that capture changes in the structure of policies. To preserve backward compatibility, we need to make sure that the existing tests pass. I don't think that anything else is required.
