### ISSUE TITLE
Define IT attributes versioning 

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1679]
Please update or continue https://github.com/fybrik/fybrik/pull/1670.
And define a backward compatibility mechanism.

**Comment by shlomitk1** [comment]
IT attribute structure is a part of Fybrik code/release thus there is no point to separate IT attrubute versioning from Fybrik versioning.

**Comment by shlomitk1** [comment]
To preserve backward compatibility, we need to make sure that the existing tests are passing. I don't think that anything else is required.

**Comment by simanadler** [comment]
@shlomitk1 I'm not sure this is true.  Please remember that the structures used for IT config policies and attributes are no different than a CRD.  They are customer facing.  Just as CRDs are versioned differently from the version of Fybrik, shouldn't the policies be versioned as well?

The customers will potentially have 10s or 100s of policies, which they are not going to update for every minor Fybrik release.  Granted, we hope they won't change with every minor release.  However, that's true with CRDs as well.

**Comment by roytman** [comment]
@simanadler we probably understand backward compatibility differently.  Let's meet and talk, I'll schedule a meeting.

**Comment by shlomitk1** [comment]
CRDs have a built-in version field (non-optional). You can't create a CRD without specifying the version. As for *.json and *.rego files there are no such fields. Do you suggest we add such field?
Infrastructure.json is a json file. We could add a "version" key to it along with "metrics" and "attributes". Making "" equal to the minimal version (1.0 or whatever is decided).
As for .rego files - making the version as part of the package name?
