### ISSUE TITLE
Manager breaks taxonomy.Connection structure defined in the taxonomy

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#1689]
The problematic scenario is that the user uses taxonomy.Connection structure as follows, while the manager generates 
taxonomy.Connection structure in the write flow as shown below which does not match the taxonomy defined by the user.

The taxonomy.Connection that is used:
```
"details": {
		"connection": {
			"name": "catalog",
			"additionalProperties": {
				"assetProperties": [],
				"columns": [],
				"connectionProperties": {
					"name": "s3",
					"s3": {
						"bucket": "...",
						"endpoint": "...",
						"object_key": "..."
					}
				},
			}
		},
		"dataFormat": "csv"
	},
```

the taxonomy.Connection that is generated by the manager:
https://github.com/fybrik/fybrik/blob/master/manager/controllers/app/plotter_generator.go#L76

```
connection := taxonomy.Connection{
		Name: cType,
		AdditionalProperties: serde.Properties{
			Items: map[string]interface{}{
				string(cType): map[string]interface{}{
					"endpoint":   bucket.Endpoint,
					"bucket":     bucket.Name,
					"object_key": genObjectKeyName,
				},
			},
		},
	}

**Comment by revit13** [comment]
related to [#discss](https://github.com/fybrik/fybrik/discussions/1695)

**Comment by shlomitk1** [comment]
Will be resolved as a part of https://github.com/fybrik/fybrik/issues/1737

**Comment by flora177** [comment]
This is open as a place holder, although this is not a problem for open source
