### ISSUE TITLE
Add liveness and readiness probs to manager

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1702]
We need to add liveness and readiness probes to manager

Here is an example https://github.com/kubernetes-sigs/controller-runtime/pull/856/files

Some relevant discussions  - https://github.com/operator-framework/operator-sdk/issues/1234

**Comment by shlomitk1** [comment]
Metric service is enabled when the manager is deployed with cluster permissions and `prometheus` set to true:
`{{- if and .Values.clusterScoped .Values.manager.prometheus }}`

**Comment by roytman** [comment]
the issue is not about the metric service
