### ISSUE TITLE
Set fybrikstorageaccounts.app.fybrik.io  as an optional

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1717]
In some use cases, fybrikstorageaccount is not used. 
Please check possibility to change this CRD deployment as an optional.

**Comment by shlomitk1** [comment]
FybrikStorageAccounts are always used. It is an input to the optimizer. Even if none are deployed, the CRD should be deployed.

**Comment by roytman** [comment]
it is not always used, and we are asked to do it optional

**Comment by shlomitk1** [comment]
A requirement to https://github.com/fybrik/fybrik/issues/1737

**Comment by laurieaw63** [comment]
Is it possible to make this optional? As Alexey pointed out there are environments where this CRD will not be required and must not be installed due to certification reasons.

**Comment by roytman** [comment]
Meantime, we decided that FybrikStorageAccount CRF would not be optional. Closing.
