### ISSUE TITLE
Helm client throttling

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1740]
Fybrik deployments on OCP clusters (some of them)
creates helm client throttling and delay module deployment for 1.156 s

I0926 17:27:21.448347     141 request.go:665] Waited for 1.156481339s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/snapshot.storage.k8s.io/v1?timeout=32s

The attached 2 logs one (god) from IKS deployment and another (bad) from OCP. 
[cloud-1.1.0-good.log](https://github.com/fybrik/fybrik/files/9657778/cloud-1.1.0-good.log)
[ocp-1.1.0-bad.log](https://github.com/fybrik/fybrik/files/9657779/ocp-1.1.0-bad.log)

P.S. I tried `perm-helm` tool on datamesh06, but could not reproduce the issue.

**Comment by shlomitk1** [comment]
Not related to Fybrik, this is a well-known kubernetes issue:
https://jonnylangefeld.com/blog/the-kubernetes-discovery-cache-blessing-and-curse

**Comment by roytman** [comment]
Correct, but it can be resolved by configuration of the QPS/Burst settings K8s client. This issue is to check how it can be done for the internal kube client instance used by the helm library to do the install

**Comment by roytman** [comment]
closed by #1741
