### ISSUE TITLE
Optimizer: add a constraint that matches StorageAccount type and the relevant module protocol

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1747]
For example: If a copy module with s3 protocol is chosen, the selected storage account type should be s3.

**Comment by simanadler** [comment]
Should the storage account type determine the copy module chosen, or should the copy module protocol determine the storage account type?  

Perhaps this should be discussed as part of the requirements and design work for storage types, prior to opening this issue?
