### ISSUE TITLE
Create a vault plugin to read credentials from OpenMetadata

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1755]
OpenMetadata catalog stores credentials to the data stores, when a module needs to read or write data into a data store, the module needs the relevant credentials. 
We need to provide a mechanism to pass these credentials from OpenMetadata catalog via vault to the module.

**Comment by shlomitk1** [comment]
Why is there a need in a dedicated vault plugin? There are other options that can be leveraged such as vault k8s plugin, storing a secret in vault...

**Comment by roytman** [comment]
Shlomit, Hashicorp came with vault to replace K8s secretes with a more secure solution. Now you suggest to use K8s secrets with vault, why? In this case is better to use K8s secrets directly.

**Comment by shlomitk1** [comment]
I don't suggest to use secrets with vault. Storing credentials in a vault path is perfectly fine. I just don't understand why you need to write yet another plugin to vault instead using vault libraries for storing/retrieving a secret.

**Comment by cdoron** [comment]
closed by https://github.com/fybrik/vault-plugin-secrets-omd-reader/pull/1
