### ISSUE TITLE
Duplicate datacatalog.json creation

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1764]
The [make generate](https://github.com/fybrik/fybrik/blob/c13d67f0c5d2134a1a4b22e1b6d748234ccccc09/Makefile#L16) targets creates json taxonomy files in `charts/fybrik/files/taxonomy/`. It has two steps, the first step runs over  CRDs (`./manager/apis/app/v1beta1/`) and the second one over  model files (`./pkg/model/`).
They should create different files, however, both of them create `datacatalog.json`. 
The difference in the files are `CreateAssetResponse`, `UpdateAssetRequest` and `DeleteAssetResponse`.

looks like the first step creates a wrong file, and the file should be created only once.

**Comment by rohithdv** [comment]
If we check the folder `./manager/apis/app/v1beta1/`, there are these structs `FybrikApplicationSpec` and `FybrikModuleSpec`  in `fybrikapplication_types.go `and `fybrikmodule_types.go ` respectively. Only these two structs are marked with the `+fybrik:validation:object` tag so the `json-schema-generator` will generate json-schema in  `fybrik_application.json` and `fybrik_module.json` with these two structs and the corresponding fields inside these go structs. These two go structs internally use `ResourceColumn`, `ResourceDetails` and `ResourceMetadata` go structs from `pkg/model/datacatalog`  and these are put in `datacatalog.json` by the `json-schema-generator`.

For example, in `FybrikApplicationSpec` go struct there is a `DataContext` object which has a `DataRequirements` object which in turn has a `FlowRequirements` object which inside it has a `datacatalog.ResourceMetadata ` object (imported from `pkg/model/datacatalog`). 

When the second command in the make generate target is executed, it is passed `pkg/model/datacatalog` and it also parses the `ResourceColumn`, `ResourceDetails` and `ResourceMetadata` go structs and recreates the `datacatalog.json`. 

Basically whenever a go struct is parsed from `pkg/model/datacatalog` package it is put in `datacatalog.json` by the `json-schema-generator`. This is the implementation of the `json-schema-generator` as of today. 

In the first command in [make generate](https://github.com/fybrik/fybrik/blob/c13d67f0c5d2134a1a4b22e1b6d748234ccccc09/Makefile#L16), it encounters only these 3 go structs  - ResourceColumn`, `ResourceDetails` and `ResourceMetadata` go structs  during the parsing of `./manager/apis/app/v1beta1/` folder and hence it puts these 3 structs in `datacatalog.json`. 

In the second command of [make generate](https://github.com/fybrik/fybrik/blob/c13d67f0c5d2134a1a4b22e1b6d748234ccccc09/Makefile#L16), it encounters the above 3 structs (defined in the `pkg/model/datacatalog/model.go`) as well as additional go structs defined in `pkg/model/datacatalog/api.go`) during the parsing of `./pkg/model/...` folder and hence it also creates (overwrites) the `datacatalog.json` with these go structs information. 

Now with this understanding, can you please let me know what changes need to be done? Thanks! @roytman

**Comment by roytman** [comment]
Partially resolved by https://github.com/fybrik/json-schema-generator/pull/56#pullrequestreview-1264805459
