### ISSUE TITLE
Copy flow fails to register the new asset in Katalog

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1789]
RegisterAsset complains that the new asset name is illegal since the original "ns/name" is used as the prefix.

**Comment by simanadler** [comment]
Is this still relevant?  Quick start now uses Open Metadata.  Is katalog used in unit tests, and thus this is still relevant?

**Comment by shlomitk1** [comment]
Katalog is not used in unit tests. Still, it's a bug in the CreateAsset implementation of the katalog connector.
