### ISSUE TITLE
OpenMetadata Instruction Comments

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1800]
1) OpenMetadata tag instructions in https://fybrik.io/dev/tasks/omd-discover-s3-asset/
OpenMetadata has tag categories.  If I understand correctly they are meant to correlate with business and regulatory guidelines / terms.  I see there is a category tiers, PII, and personal data.  

a) We have added as part of our deployment a category Fybrik, under which there is PII and finance.  Can we remove the Fybrik category?  We could use the existing PII category.
b) Similarly, I would suggest adding a category called Purpose and put finance there rather than under Fybrik.

2) Please add a section on how to delete an OpenMetadata deployment, perhaps as an optional cleanup step in https://fybrik.io/dev/samples/cleanup/

3) Step 24 in https://fybrik.io/dev/tasks/omd-discover-s3-asset/ is unclear.  Please expand on who/what (fybrik manager) uses these customer properties and the purpose of the different fields

**Comment by cdoron** [comment]
I have addressed your second point: https://fybrik.io/dev/samples/cleanup/
Regarding your other comments, let's discuss.
Thanks

**Comment by cdoron** [comment]
- [ ] Change OpenMetadata connector to create Tag Properties as needed. For instance, if an asset is tagged with `Purpose.Housing`, create category `Purpose` if it does not exist, and create tag `Housing` if it does not exist
- [ ] Add an error message stating a custom property is missing
- [ ] Update documentation to explain why Custom Property fields are needed
- [ ] Change the name of the `Name` custom property field to `Description`
- [ ] Owner - take owner from OpenMetadata
- [ ] Replace `geography` custom property with `Geography` tag category

**Comment by cdoron** [comment]
most points were addressed by:
- https://github.com/fybrik/openmetadata-connector/pull/36
- https://github.com/fybrik/fybrik/pull/1825

The rest of the points were moved to https://github.com/fybrik/openmetadata-connector/issues/49
