### ISSUE TITLE
Extract taxonomy related CLI commands from the Fybrik main repository

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1832]
Currently, taxonomy CLI commands are part of the main Fybrik repo. That creates several issues:

1. conflicts with their dependencies prevents upgrade Fybrik third-party components. And prevents resolving security alerts in these third-party components. 
2. The main fybrik file points to these CLI commands only, which is misleading and complicates understanding Fybrik's code.

**Comment by roytman** [comment]
Good idea, the docker image will eliminate existing golang requirement.

**Comment by roytman** [comment]
The work plan:

- Copy the taxonomy CLI files ([main.go](https://github.com/fybrik/fybrik/blob/master/main.go), [cmd/,](https://github.com/fybrik/fybrik/tree/master/cmd), [compile/](https://github.com/fybrik/fybrik/tree/master/pkg/taxonomy/compile), [validate/](https://github.com/fybrik/fybrik/tree/master/pkg/taxonomy/validate), maybe some others)  into a new repository.
- Remove the import comments in [structural.go](https://github.com/fybrik/fybrik/blob/master/pkg/taxonomy/validate/structural.go), and `//go:build exclude` in [structural.go](https://github.com/fybrik/fybrik/blob/master/pkg/taxonomy/validate/structural.go) and [taxonomy_validate.go](https://github.com/fybrik/fybrik/blob/master/cmd/taxonomy_validate.go)
- Check that the `taxonomy compile` and `taxonomy verify` operations can work with the new repository.  Fybrik [Makefile ](https://github.com/fybrik/fybrik/blob/03ea624faa4bfc53c735aa2a69700b066e4c2056/Makefile#L94) and/or with a [custom taxonomy](a Custom Taxonomy)
- Create a Docker that can be used for the taxonomy compilation, validation, similar to [openapi-generator-cli ](https://github.com/fybrik/openmetadata-connector/blob/dd03efa283d24a11c2587c71bfc01b71cc1cfa2b/Makefile#L39), see https://github.com/OpenAPITools/openapi-generator#16---docker
- Create the docker image and push it into a public repository
- Update the main Fybrik repo to use the docker image, update its web pages, and remove the redundant files.

**Comment by shlomitk1** [comment]
Might be helpful - some info from my attempt to generate a container (ghcr.io/shlomitk1/taxonomy-compiler:master)
- Makefile target to build an executable
```
.PHONY: taxonomy-build
taxonomy-build:
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -o taxonomy_compiler main.go
```
- Dockerfile to create the image
```
# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
ARG image=registry.access.redhat.com/ubi8/ubi-minimal:8.6
FROM $image
ENV HOME=/tmp
WORKDIR $HOME
COPY taxonomy_compiler /
USER 10001

ENTRYPOINT ["/taxonomy_compiler"]
```
- Test container locally in fybrik root dir
`docker run --rm -u "$(id -u):$(id -g)" -v ${PWD}:/local ghcr.io/shlomitk1/taxonomy-compiler:master taxonomy compile --out /local/custom-taxonomy.json --base /local/charts/fybrik/files/taxonomy/taxonomy.json /local/samples/taxonomy/example/catalog/connection.yaml`
