### ISSUE TITLE
Feature Request: Need Fybrik Manager to understand message from Catalog Connector and persist them in the fybrikapplication

### ISSUE THREAD

**Issue by Ashwinira** [fybrik/fybrik#1858]
Whenever a client interacts with fybrik platform to retrieve the fybrik application details, any info/warn/error messages received by the catalog connector must be surfaced to the client.  When the catalog connector retrieves asset details or policy decisions from the catalog, there might be some additional messages that the connector wants to return back to the fybrik.(ex. some informative message, some warning regarding the user access or error message). We want the fybrik manager to populate such messages in the fybrikapplication such that when the client checks for the status of the asset by doing a describe on the  fybrikapplication, the client can know the exact reason behind the status .

ex. 

- If it is error, then we can know the exact reason behind the failure.
- If it is deny we can know the reason behind the Denial.
- If it is Ready and the connector wants to pass on some informative message, then we can pass it and see it in the fybrikapplication.

Can fybrik manager accept the message from connector and persist it in the fybrikapplication.

**Proposed message format:**

```
"message": {
	"code": "FYBMG0001W",
	"level": "WARN" / "INFO" / "ERROR",
	"description": "some message description/ error message/ some warning"
}
```

**Expected Structure of fybrikapplication:**

```
"assetStates": {

	"{\"asset_id\": \"d7d6d11f-d428-400e-84b1-62c437730fde\", \"context_type\": \"catalogs\", \"context_id\": \"ac29f567-50fd-476f-8c31-a670532f4c73\"}": {

		"conditions": [{

				"message": {

					"code": "FYBMG0001W",

					"level": "WARN / INFO / ERROR",

					"description": "some message description"

				}

				"status": "True",

				"type": "Ready"

			},

			{

				"status": "False",

				"type": "Deny"

			},

			{

				"status": "False",

				"type": "Error"

			}

		],
```

**Comment by roytman** [comment]
Hi @Ashwinira, thanks for the issue, we will evaluate your suggestion.

**Comment by shlomitk1** [comment]
The current policy of manager is to leave the most recent message, i.e., it does not accumulate messages, which may be ok for error/deny states. As for the ready state of the asset, do we want to accumulate messages (there may be one from catalog, another - from policy manager, storage allocator)? Also, where are the messages stored when the application is not ready, yet it is not an error? Perhaps to have additional field(s) for informative messages, per asset but outside the conditions?

**Comment by Ashwinira** [comment]
For now we see its okay to leave the most recent message. We will keep you posted if in future we have a requirement to accumulate the message. Regarding this `Also, where are the messages stored when the application is not ready, yet it is not an error? `we are not sure about the scenario when this situation arises. But connector's message will not help here as they are specific to the asset.

**Comment by shlomitk1** [comment]
Per discussion with @Ashwinira, the connectors will send a JSON string containing the mentioned fields (level, code, text), so no changes in CRDs are needed.
