### ISSUE TITLE
Timeout errors in the github actions

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1860]
From time to time, some of the notebook samples test fail with messages like `panic: test timed out after 10m0s`. 
[2_Read flow notebook sample (old).txt](https://github.com/fybrik/fybrik/files/10335294/2_Read.flow.notebook.sample.old.txt)
[Read flow notebook sample (old).zip](https://github.com/fybrik/fybrik/files/10335298/Read.flow.notebook.sample.old.zip)

**Comment by revit13** [comment]
This issue might be fixed in https://github.com/fybrik/fybrik/commit/e2d12d826ca8c765c82b5e8cdc72175410266304 which contains a fix for [multiple fybrikapps to fight race-condition](https://github.com/fybrik/fybrik/pull/1956/commits/0c58d9bb1a29cb9fab37570f565501e928ef06c7).

**Comment by shlomitk1** [comment]
A possible reason might be that port-forwarding of the read service is done too early, before the server running in the pod actually opens the port. When FybrikApplication is ready, it does not necessarily mean that the server is up and running. It only means that the pod is up. Inserting a delay between catching a ready status and port-forwarding would probably solve the issue.
