### ISSUE TITLE
Difficult to understand if Fybrik tests pass

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#1861]
When running `make test` of fybrik, tons of log info is printed out including errors. Those errors may be valid if a negative test is being run.  For the end user trying to figure out if they have a valid and working installation of fybrik, It's not possible to figure out if all the tests passed or not without scrolling through thousands of lines of logs.

@shlomitk1 said that 'I think that when we moved to ginkgo 2.0 instead of 1.0, we started seeing full logs... Needs to be checked."

**Comment by shlomitk1** [comment]
After a further investigation, it seems that ginkgo has fixed a problem of not obeying the verbosity flag. Indeed, when we run `go test ./...` instead of `go test -v ./...`, printing is done only for failing tests.
