### ISSUE TITLE
A workflow calls a nonexistent make target

### ISSUE THREAD

**Issue by Vicky-Goldin** [fybrik/fybrik#1872]
In [debug_build.yml](https://github.com/fybrik/fybrik/blob/v1.2.0/.github/workflows/debug_build.yml#L41) the workflow attempts to run `make docker`, but there is no `docker` target in the [root makefile](https://github.com/fybrik/fybrik/blob/v1.2.0/Makefile).
The workflow was never run in ['Actions'](https://github.com/fybrik/fybrik/actions/workflows/debug_build.yml).

**Comment by roytman** [comment]
Hi @Vicky-Goldin , thanks for the issue.
I fixed the workflow targets. 

The purpose of the workflow  is to generate and push images into the repository. It doesn't execute automatically, but requires a manual start.
