### ISSUE TITLE
OneClickDemo doesn't list its requirements

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1912]
The OneClickDemo doesn't mention requirements to run the scripts. The requirements can be a pointer to the `Quick Start` page, but it should explicitly mention that the scripts require Linux or Mac OS with running `docker`  and `kind` should be deployed.

**Comment by aradhalevy** [comment]
the page does mention requirements, just not with a proper title requirements. 
it is under the number 6 of the demo sequence:

"All your require for the demo is a working bash terminal and docker installed.
The demo will make a bin folder at your current directory with all the required dependencies for Fybrik."

`kind` doesn't need to be deployed before the Demo, it is installed in the bin folder and deployed as part of the script.

I think it is best that we add a requirements title, and also mention docker needs to be deployed, not only installed. @roytman sounds good? 

also, you are right we should replace  "a working bash terminal" with "Linux or MacOS", it is more accurate.

**Comment by roytman** [comment]
>I think it is best that we add a requirements title, and also mention docker needs to be deployed, not only installed. @roytman sounds good?

yes,

>also, you are right we should replace "a working bash terminal" with "Linux or MacOS", it is more accurate. 

actually it doesn't work on Mac, see #1914, so I suggest to add a comment about Linux, and later after fixing @1914, add MAC too.
