### ISSUE TITLE
Check how can we modify data, from Mysql

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1918]
If data is being read from Mysql, how can we modify it? 
Can we change airbyte connector select request?
Can we connect another module for the transformation?
Something else ....

**Comment by Mohammad-nassar10** [comment]
Option 1 - Modify sql query: We can't customize the select query that pull data from Mysql or choose which columns to fetch from the database ([source](https://discuss.airbyte.io/t/mysql-source-loading-from-sql-query-not-tables-views/620)). A possible solution is to add changes to the Mysql connector of Airbyte.

Option 2 - Add transformation (action) code to the `airbyte-module`. The `airbyte-module` runs two servers, `http` server and `arrow-flight` server. For `arrow-flight` server we can add the same code from `arrow-flight-module` that handles the transformations in `do_get()` function. Also, in `http` server we can add transformations on the pulled data.

Option 3 - Add python library that includes transformations (actions) and use it in `airbyte-module`. (Possible next step is to extend this to plugins of actions).
