### ISSUE TITLE
Update v 1.2.1 and master samples documentation  

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1939]
Due to long time required to install OpenMetadata catalog we need to provide a faster option - working with Katalog.

Please update getting starting and notebook samples examples to allow working with both catalogs. 
The documentation should be updated for v1.2.1 and master.

**Comment by cdoron** [comment]
The following PRs address this issue:
https://github.com/fybrik/fybrik/pull/1926
https://github.com/fybrik/fybrik/pull/1934
https://github.com/fybrik/fybrik/pull/1935
https://github.com/fybrik/fybrik/pull/1941

**Comment by roytman** [comment]
@cdoron , we will need similar PRs to the master. 
why did you set the issue as blocked ?

**Comment by cdoron** [comment]
> @cdoron , we will need similar PRs to the master. why did you set the issue as blocked ?

https://github.com/fybrik/fybrik/pull/1951 updates documentation on master
