### ISSUE TITLE
Leverage new functionality of Helm to show the status of deployed resources

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1969]
According to the documentation: `The Helm status command and the SDK can now show the status of core resources deployed in a chart (e.g., deployments). To use with helm status you need to use the --show-resources flag.`
Currently, Fybrik code (helm package) implements this functionality by getting resources from helm manifest and use k8s client to get their current status. If the imported helm code can do this instead, we don't need this implementation in Fybrik, just need to use the SDK correctly. This could increase run-time performance by eliminating some calls to helm and k8s.

**Comment by roytman** [comment]
Fybrik use helm 3.11.1 now.
