### ISSUE TITLE
Different base container mages used by Fybrik

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#2013]
Fybrik uses different base container images, e.g. ubi8/ubi:8.7 and ubi8/ubi-minimal:8.7.

 ubi8/ubi:8.7 doesn't include `microdnf` so the checks of PR #2008 fail. We have to check if we can install `microdnf` or use another image.

**Comment by revit13** [comment]
What tool needs to be installed using `microdnf`?

please [see](https://developers.redhat.com/blog/2019/05/31/working-with-red-hat-enterprise-linux-universal-base-images-ubi): 
```
The main difference between the ubi and ubi-minimal images is that the first provides the full yum toolset. Yum adds some dependencies such as Python packages. In contrast, the second provides microdnf as a replacement. The microdnf tool works from the same repositories as Yum, but only provides the ability to install, update, and delete packages:

**Comment by revit13** [comment]
I just saw @lappanna PR. maybe the RUN command can also be passed as a parameter along with the image such that in the case of ubi image it will use Yum instead of `microdnf`

**Comment by roytman** [comment]
adding a new parameter can lead to mistakes and errors, like we've seen with the IMG. It can be the last resort. 
Can you check if there are other possibilities?

**Comment by revit13** [comment]
OK I will check. just FYI, there is a default value for the ARG(s).

**Comment by shlomitk1** [comment]
Why is Fybrik base image configurable? Any reason not to stay with ubi-minimal?

**Comment by revit13** [comment]
One of the [tls test](https://github.com/fybrik/fybrik/blob/master/charts/fybrik/notebook-test-readflow.tls-system-cacerts.yaml) implements the scenario where the CA certificates of the components in `fybrik-system` namespace are copied directly to `/etc/ssl/certs/` directory in the manager/connector pods. ubi-minimal image has a minimal set of tools and thus lack the tools to copy the certificate. This is why ubi image was used instead. An alternative was to use ubi-minimal image and install the tools with microdnf.

**Comment by revit13** [comment]
One of the tls tests copies CA certificates of the components in `fybrik-system` namespace to `/etc/ssl/certs/` directory in the manager/connector pods thus needs a tool that is needed for the copy operation and is missing from the ubi-minimal image. One of the options was to install the required tool with microdnf instead of using ubi image. I will try to return to this option. Thanks
