### ISSUE TITLE
Clear FybrikApplication selector for chained modules.

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#2048]
In chain deployments, the FybrikApplication selector is relevant to the module that is the data plane entry point. The selector is used for NetworkPolicies creations. 
In the current implementation, a workload is able to skip the starting data plane module and connect to the next one. 
For example, in our [FybrikModule chaining sample](https://fybrik.io/v1.3/samples/chaining-sample/), if the entry point of read module (airbite) is known, a workload can skip the transformation (PII data reduction) module (arrow-flight). 

The selector is relevant to only modules which can be accessed by user workloads.

**Comment by roytman** [comment]
The issue is relevant to #2037 , in both a blueprint module deployer should have exact information who can connect to the module.

**Comment by shlomitk1** [comment]
Part of https://github.com/fybrik/fybrik/issues/2047
