### ISSUE TITLE
when running the QuickStart readflow, AWS CLI doesn't accept "theshire" as a Region

### ISSUE THREAD

**Issue by aradhalevy** [fybrik/fybrik#2052]
when running manually the QuickStart, when you get to the part where you need to[ register your asset to localstack](https://fybrik.io/v1.3/samples/notebook-read/#prepare-a-dataset-to-be-accessed-by-the-notebook:~:text=For%20experimentation%20you,%24%7BFILEPATH%7D), 
configuring REGION as "theshire" produces an error - 
 
 "An error occurred (InternalError) when calling the PutObject operation (reached max retries: 2): exception while calling s3.PutObject: 'theshire' is not a valid AWS region name for s3"

I am using aws-cli/2.7.21

local stack was installed using the commands specified in the read flow

**Comment by revit13** [comment]
@aradhalevy can you please provide the version of the aws client you use? Thanks
