### ISSUE TITLE
Insecure communication of liveness and readiness probs

### ISSUE THREAD

**Issue by ityuhui** [fybrik/fybrik#2071]
The task https://github.com/fybrik/fybrik/issues/1702 introduces liveness and readiness probs to Fybrik manager, but it's not using HTTPS.

Pen tests now report this as a problem: 

130288: Insecure communication (Low)
Description
If requests are sent without SSL/TLS implementation, then all the communication data will be sent in clear text on the network. Any user in shared network can sniff these data and get sensitive information like authentication credentials, session details, personal data, etc. Reference:https://www.cvedetails.com/cwe-details/319/Cleartext-Transmission-of-Sensitive- Information.html.

**Comment by ityuhui** [comment]
Hi @revit13 

Is this task working on progress ? We look forward to this fix. Thanks !

**Comment by revit13** [comment]
@ityuhui Hi, I was trying to set `scheme: HTTPS` in the probes but I get an error because the controller is not configure with TLS.
I posted a question in the `controller-runtime` repo: https://github.com/kubernetes-sigs/controller-runtime/issues/2283.
We are still looking into that and update as soon as we get a fix. Thanks
```
 Readiness probe failed: Get "https://10.244.1.10:8088/readyz": http: server gave HTTP response to HTTPS client

**Comment by ityuhui** [comment]
I think this problem goes away as soon as there is no HTTP server port.
And applying for an exception is another option.

Let's discuss it in your meeting.

**Comment by roytman** [comment]
After checking the K8s controller-runtime code and discussion at the relevant issue, we got [conformation](https://github.com/kubernetes-sigs/controller-runtime/issues/2283) that the controller-runtime "always serves the probes with http."
I'm closing the issue for now.
