### ISSUE TITLE
Define and enforce a taxonomy

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#238]
An end to end solution requires a taxonomy to be defined and used across different components. The Mesh for Data includes core components (mainly defined in `manager` and `pkg`) and plugins (`connectors` and `modules`). Currently, partial and hardcoded definitions are defined across both core components and plugins.

Design document is available in: https://docs.google.com/document/d/1sfdcNI6PTIYWsSIznpNqJNQCdVaVFchYB2vljzUrlew/edit?usp=sharing

**Comment by simanadler** [comment]
I'm assuming we will define our taxonomy as json schema files.  Thus, we will need a json schema validator to use within our code.  For gaoling code, is this an acceptable library or is there something else you recommend?  https://github.com/xeipuuv/gojsonschema. @roee88

**Comment by roytman** [comment]
Done
