### ISSUE TITLE
Release: improve image tags for public images

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#499]
Push public images using unique tags.

The current behavior is:
- Releases are pushed as release version (X.Y.Z) 
- master is pushed as latest

The expected behavior is:
- Releases are pushed as release version (X.Y.Z) and latest
- Branches are pushed using branch name (i.e. master)

Ref: https://github.com/IBM/the-mesh-for-data/pull/496#issuecomment-815134116

**Comment by revit13** [comment]
@roee88 a question - currently images can be deployed with corresponding charts - https://github.com/fybrik/charts use the image of the latest release and the development version uses the image of master branch. this issue talks only about the images without the charts - if we deploy images for branch x then to use it we will have to change the deployments manually right? Also, what branches we would like to create images for? except for master there are the releases/  but those already exists in our repo.

**Comment by roee88** [comment]
> @roee88 a question - currently images can be deployed with corresponding charts - https://github.com/fybrik/charts use the image of the latest release and the development version uses the image of master branch. this issue talks only about the images without the charts - if we deploy images for branch x then to use it we will have to change the deployments manually right? 

When installing a chart you can specify the tag to use, I'm not sure what you're asking.

> Also, what branches we would like to create images for? except for master there are the releases/ but those already published

All branches except for site and `releases/*`. Starting with the next release we will start using a branch per minor release and cut patch tags from it.

**Comment by revit13** [comment]
@roee88 Thanks. Also, I see you already did the change to use PUBLIC_TAG (called now DOCKER_PUBLIC_TAGNAME) as you mentioned in comment #496
