### ISSUE TITLE
Razee: weird error reports after a blueprint is idle for some time

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#535]
Data usage scenario: a "read" blueprint running in a local cluster, a "copy" blueprint running in a remote cluster.
After some time since the blueprints have become ready, manager reports an error:
ERROR	RazeeManager	Error while fetching resource content of blueprint	{"cluster": <cluster name>, "name": <blueprint name>, "error": "invalid character '<' looking for beginning of value"}

**Comment by roytman** [comment]
@shlomitk1, I assume that you don't have any updates, correct?

**Comment by shlomitk1** [comment]
I have not checked since last October...

**Comment by shlomitk1** [comment]
No longer reproducible, closing.
