### ISSUE TITLE
Isolation between deployed components

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#56]
## Problem statement

The control plane deploys modules as part of a blueprint orchestration. These modules augment the data path that originally contains the application workload and data sources, with additional data centric functions. However:
1. A module can currently be used by any workload in the cluster rather than forcing the data flow to match the desired state
1. A module can currently access any endpoint so a hijacked module can leak data
1. An application workload can access any endpoint so it can leak data

## Proposed approach

This is a broad topic that has a lot of dependencies. We should start by creating a NetworkPolicy to restrict access to the blueprint namespace such that only the workload referenced in the M4DApplication resource can access it (this does not yet enforce the desired flow but improve the current state).

A follow-up is to improve the blueprint specification such that a network graph can be deduced from it (e.g., from a data flow graph; neither of which currently exist in the blueprint specification). Then we would have the desired flow to enforce.

The last part is enforcing the flow by creating NetworkPolicies and Istio resources. Specifically, a rough sketch of the proposal is to:
1. Use NetworkPolicies to enforce the flows between the blueprint components running in the cluster based on labels
1. [optional] Use Istio authorization policies to enforce the flows between the blueprint components running in the cluster based on identities
1. Make a gateway be part of any blueprint
1. Route all external traffic through the gateway 
1. Use Istio authorization policies in the gateway to restrict what external endpoints each identity can access

A technical approach on how to implement it to be proposed later as we already have a lot of this from earlier attempts.

## Related items

1. Virtual endpoints to expose dataset connection endpoints that are not tied to the physical endpoint

**Comment by simanadler** [comment]
The only explicit information we have about the workload is its label(s), which is included in m4dapplication. Am I correct in assuming that in order to implement isolation we would have to use k8s apis to obtain the actual resources associated with the label, it's IP address, etc in order to do the workload isolation? @roee88

**Comment by roee88** [comment]
The project has evolved significantly since the opening of this issue. While isolation is still not addressed, the details within this issue are probably irrelevant.

**Comment by simanadler** [comment]
@roee88 Do we have a different issue open with relevant details?

**Comment by roee88** [comment]
No. A discussion can be opened once there is a need to do something.

**Comment by simanadler** [comment]
@roee88 I would suggest leaving an open issue in our backlog, so that we don't loose track of the fact that we need to do something

**Comment by roee88** [comment]
Feel free to open a new one. In general though, issues are only for actual work items and this one isn't (it pre-dates our move to using discussions).
