### ISSUE TITLE
Smart Blueprint: Config Policies and IF Design

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#614]
Detailed design for:
1) How to use the policy engine  to be used for config (non-governance) policies, including some example policies
2) M4D Interface for interacting with the chosen policy engine 

Parent Issues: #93

Dependencies: Issue #612 #593

**Comment by shlomitk1** [comment]
Document for the detailed design:
https://docs.google.com/document/d/1l7TmlacPjXGQJ_83OiJHYa40P_SL-YiQgxAcZqzyr_M/edit

**Comment by simanadler** [comment]
Based on the review yesterday, the next step is to write a user guide describing how to write hard config policies. @shlomitk1

**Comment by shlomitk1** [comment]
Implemented in #932
