### ISSUE TITLE
Show status per asset for fybrikapplication

### ISSUE THREAD

**Issue by lappanna** [fybrik/fybrik#640]
Currently we do not see a status per asset level in m4dapplication. If we get per asset status as below, it will be helpful.

```
Status:
     - Asset_id: <asset_id_1>
         Catalog_id: <catalog_id_1>
         Message:  < asset does not exist etc>
         Status:             False
         Type:               Deny
         Status:             True
         Type:               Error
     - Asset_id: <asset_id_2>
         Catalog_id: <catalog_id_2>
         Message:  < Deny etc>
         Status:             True
         Type:               Deny
         Status:             False
         Type:               Error
    Status:             True
    Type:               Failure
    Status:             False
    Type:               Error

**Comment by shlomitk1** [comment]
We have also some other information about a data asset: provisioned bucket if copy is needed, a virtual endpoint for data consuming. Should these be reflected as well?

**Comment by lappanna** [comment]
Virtual endpoint for data consuming is required, I'm not sure on provisioned bucket for copy.

**Comment by roee88** [comment]
@shlomitk1  provisioned bucket is internal information, isn't it?

**Comment by shlomitk1** [comment]
> 
> 
> @shlomitk1 provisioned bucket is internal information, isn't it?

Right.

**Comment by shlomitk1** [comment]
@lappanna Is Ready required for each dataset status as well?

**Comment by lappanna** [comment]
@shlomitk1 yes, we wanted to have status for each dataset.

**Comment by shlomitk1** [comment]
@lappanna Given that every asset has its own state, what is the semantics of Ready in the application status? 
I would assume that application is Ready if all specified assets are in "final" state, i.e. either Ready or Deny. Is my assumption correct?

**Comment by rachit1arora** [comment]
@shlomitk1 : Yes, I agree with your assumption. Application state is cumulative state of all assets.

**Comment by shlomitk1** [comment]
@lappanna @rachit1arora 
In the case when the same asset is used in different flows, e.g. it is copied to another location and also is read by the workload, do you want to get the status of the asset per each flow (ready for being read but not yet copied) or the overall status of the asset?
cc @simanadler

**Comment by rachit1arora** [comment]
@shlomitk1 Just to clarify your question and scenario. 
If an asset is being used in multiple fybrik applications and your question is if we should give the status of asset per application with respect to that application whether it is read only or Copy copy, then yes that is our intent and not overall combined status for the asset. Status of the asset in that application need to be with respect to application it is being requested. I hope this clarified your question. Let me know if more info is required from our side 

cc: @lappanna
