### ISSUE TITLE
Restrict manager access to a specific namespace for some resources

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#671]
Except for M4DApplications, manager does not need cluster-wide access to resources. 
For example, pods and deployments are created in m4d-blueprints, m4dmodules are read from m4d-system, etc.
A new release of controller-runtime (0.9.0 and higher) enables to control manager access. 
**Required:** to upgrade controller-runtime version to 0.9.0 with all relevant dependencies.

**Comment by roee88** [comment]
Why does it need cluster wide access to secrets? Cluster wide access to secrets is an issue.

**Comment by shlomitk1** [comment]
> 
> 
> Why does it need cluster wide access to secrets? Cluster wide access to secrets is an issue.

My mistake, it does not. The secrets manager needs are from m4d-system.

**Comment by roee88** [comment]
Should we stop importing datashim and use unstructured.Unstructured instead? I'm not sure when they will upgrade to newer operator-sdk that doesn't cause so many dependency issues.

**Comment by shlomitk1** [comment]
Depends on https://github.com/mesh-for-data/mesh-for-data/issues/674

**Comment by ngoracke** [comment]
From a multi-tenancy perspective, is it possible to configure more than one mesh-for-data control plane in a single kubernetes/openshift cluster?  

Based on my experimentation, it seems that if multiple managers are installed to the same cluster, all will act on a new m4dapplication, and there doesn't seem to be a way to scope on a namespace-by-namespace basis.  I've tried adjusting clusterrolebindings -> rolebindings, but it seems the reconcilers are attempting to query cluster-wide, so this just results in errors in the manager logs.

**Comment by ronenkat** [comment]
> From a multi-tenancy perspective, is it possible to configure more than one mesh-for-data control plane in a single kubernetes/openshift cluster?
> 
> Based on my experimentation, it seems that if multiple managers are installed to the same cluster, all will act on a new m4dapplication, and there doesn't seem to be a way to scope on a namespace-by-namespace basis. I've tried adjusting clusterrolebindings -> rolebindings, but it seems the reconcilers are attempting to query cluster-wide, so this just results in errors in the manager logs.

@ngoracke at this time you can have only one instance of mesh for data, we have been following the Istio model which is one control plane per cluster. We are considering moving to a model similar that Red Hat implemented for their variant of Istio, which would allow multi tenancy.

**Comment by jlkaus** [comment]
@ronenkat is there an issue open for that work? or not yet decided to do so?

**Comment by ronenkat** [comment]
> @ronenkat is there an issue open for that work? or not yet decided to do so?

@jlkaus there is no open issue yet, it is on the "want to do", please feel free to open an issue, add requirements.
We would be happy to get help for this interesting topic.

**Comment by warren-acker** [comment]
@ronenkat Do we need a new issue or can the effort be added here?  We can certainly create a separate issue if that is desired.  For our internal cluster pipelines, developer needs, as well as customers that share a cluster with multiple CPD instances, we will all need cluster "multi-tenancy" support for all of  M4D.  Do you want assistance from our team or will this be handled by the research team?  Do you have a prioritization scheme for your git issues?
