### ISSUE TITLE
Record events in application controller

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#673]
Whenever a decision/status is changed a Kubernetes event with the details must be recorded. For example, when access is denied.

**Comment by ronenkat** [comment]
@simanadler is #926 replacing this issue?

**Comment by simanadler** [comment]
@ronenkat @roee88 This is exactly what I proposed in the Visibility design doc, and yesterday you said it would take up too many resources and isn't required .... so I removed it.

**Comment by roee88** [comment]
To be precise I didn't say anything about that. Also your proposal might have been misunderstood (or not), that happens :)

In any case, this issue is not about serviceability logs and the request was raised by Rachit Arora. You can ask him to add details. I can't find his GitHub id.

**Comment by simanadler** [comment]
It is sufficient to write these events to a log file, rather than generating kubernetes events to be stored as part of the FybrikApplication instance.
