### ISSUE TITLE
Add new openpolicyagent connector (V2)

### ISSUE THREAD

**Issue by rohithdv** [fybrik/fybrik#702]
Add new openpolicyagent connector in connectors/ (just its go code and Dockerfile)

**Comment by roee88** [comment]
@rohithdv an alternative to consider is to separate the catalog API before that, trying to make the opa connector not necessary (yet other connectors are still possible by implementing the same API). Do you think it's worth considering as part of 0.4 or should we keep it for later?

**Comment by rohithdv** [comment]
> @rohithdv an alternative to consider is to separate the catalog API before that, trying to make the opa connector not necessary (yet other connectors are still possible by implementing the same API). Do you think it's worth considering as part of 0.4 or should we keep this discussion for later?

I think it is better to get one entire flow working end to end with the openapi changes. We can change the catalog API after we do this (maybe for 0.4) but if there are any issues we can at least have one flow working for 0.4. This is my opinion. But I am open to changes in this matter. @roee88 

Also I did not yet understand the full changes for catalog API. Maybe we can discuss the changes needed for catalog API sometime soon.
