### ISSUE TITLE
Asset type "json" fails

### ISSUE THREAD

**Issue by elsalant** [fybrik/fybrik#724]
Using an asset type of "json" instead of "csv" does not work.
In the manger log:
ERROR	controller-runtime.manager.controller.m4dapplication	Reconciler error	{“reconciler group”: “app.m4d.ibm.com”, “reconciler kind”: “M4DApplication”, “name”: “heir-notebook”, “namespace”: “heir-mvp”, “error”: “get dataset info from katalog failed: rpc error: code = Unknown desc = the server could not find the requested resource (get assets.katalog.m4d.ibm.com diabetes-json”)“, “errorVerbose”: “rpc error: code = Unknown desc = the server could not find the requested resource (get assets.katalog.m4d.ibm.com diabetes-json”)

In the katalog-connector log:
In GetDatasetInfo: asset namespace is “heir-mvp asset name is diabetes-json”
2021/07/19 07:52:21 In GetDatasetInfo: asset namespace is “heir-mvp asset name is diabetes-json”

**Comment by shlomitk1** [comment]
Not able to reproduce.

**Comment by elsalant** [comment]
probably not...
