### ISSUE TITLE
Add to CI a system test with the equivalent of the quick-start and sample notebook

### ISSUE THREAD

**Issue by ronenkat** [fybrik/fybrik#756]
Add to the CI a test that will check Fybik in an equivalent manner to the instructions in the quick-start and sample notebook.

- [x] Develop a sample application (e.g., python) that uses Flight to read data
- [x] Develop a pipeline that:
  - [x] deploy Fybrik to Kind
  - [x] Setup localstack and sample data, register in Katalog
  - [x] Define policies in OPA
  - [x] Run the sample app and deploy FybrikApp
- [x] Run pipeline in github actions

**Comment by froesef** [comment]
A notebook test was created that is running all from golang.
It's deploying the opa connectors and s3mock to a kind cluster and then afterwards:
1. Loads example csv onto S3 if not already there
2. Creates the example application that is creating a read module that should redact one of the columns
3. Forwards port of arrow-flight read service to local
4. Reads the data via arrow-flight and verifies column names and that the `nameOrig` column is redacted

Notebook test: https://github.com/fybrik/fybrik/pull/801
Adding it to the CI build: https://github.com/fybrik/fybrik/pull/925
