### ISSUE TITLE
Name change wasn't propagated to project boards

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#780]
When the name of the project was changed from Mesh for Data to Fybrik, the project boards were not updated.

https://github.com/orgs/fybrik/projects

**Comment by revit13** [comment]
@simanadler except from one link that was fixed I do not see problems related to the project name. Can you please give an example of what needs to be fixed? Thanks

**Comment by simanadler** [comment]
The text in the tickets in the various projects still says M4D and mesh for data.
