### ISSUE TITLE
Quick start needs to be updated

### ISSUE THREAD

**Issue by elsalant** [fybrik/fybrik#781]
The old Quick Start (https://fybrik.io/v0.1/get-started/quickstart) still shows:
helm repo add m4d-charts https://mesh-for-data.github.io/charts
helm repo update
helm install m4d-crd m4d-charts/m4d-crd -n m4d-system --wait
helm install m4d m4d-charts/m4d -n m4d-system --wait

Maybe this webpage should be dropped...

**Comment by roee88** [comment]
We are not maintaining old snapshots of the website.

> Maybe this webpage should be dropped...

In this specific case due to the rename I think it's a good suggestion. If others agree I think a PR would be appreciated.

**Comment by roytman** [comment]
hi @elsalant , do you have any updates about the issue?

**Comment by elsalant** [comment]
Probably not relevant anymore
