### ISSUE TITLE
Connector Documentation Needs to be Improved

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#792]
I noticed a couple of issues with the connector documentation:

1) In the description of the connectors on the website, the documentation states that we use grpc but I believe we have moved to REST.  Thus the documentation should be updated.

https://fybrik.io/v0.4/concepts/connectors/

2) There is no documentation describing the interface between the control plane and each of the different type of connectors.  I.e. If someone wants to create their own connector it would be very difficult.

3) The README for each of the connectors says nothing about what the connector does.  It only says how to run/test them.

**Comment by roee88** [comment]
> In the description of the connectors on the website, the documentation states that we use grpc but I believe we have moved to REST. Thus the documentation should be updated.

FYI this is still work in progress, we didn't finish moving to REST.
