### ISSUE TITLE
Smart Blueprint: Create Component  for Config Policy Decisions

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#794]
Create a component <strike>connector</strike> to enable the fybrik control plane to query decisions from config policies.
The connector should receive the input and output defined in the [config policy design doc](https://docs.google.com/document/d/1l7TmlacPjXGQJ_83OiJHYa40P_SL-YiQgxAcZqzyr_M/edit?usp=sharing)

The [component design doc](https://docs.google.com/document/d/1l7TmlacPjXGQJ_83OiJHYa40P_SL-YiQgxAcZqzyr_M/edit?usp=sharing) provides an overview of the components in the solution for context, and requirements are detailed [here](https://docs.google.com/document/d/1l7TmlacPjXGQJ_83OiJHYa40P_SL-YiQgxAcZqzyr_M/edit?usp=sharing).

Assumptions:
* Config policies are implemented in OPA rego files
* Policy engine is OPA
* If OPA is being used for data governance policies, use the same instance if possible?

Tasks:

- [x] Define the input and output structures for the component
- [x] Move the current hard coded logic into the component
- [x] Write the detailed design for the component's interaction with OPA, and post processing after receipt of OPA decisions
- [x] Implement the default hard policies to be included with all deployments
- [x] Implement the quick start policies - hard policies which should implement the current hard coded logic
- [x] Implement the component to use OPA based hard config policies - moving us from hard coded logic to config policy based

Parent Issues: Issue #614, #93

**Comment by ronenkat** [comment]
Can we re-use the OPA connector? with a different taxonomy? should re-use of the connector be a requirement?

**Comment by simanadler** [comment]
@ronenkat The input and output are different, so I don't think we can re-use the existing connector as is and thus it shouldn't be a requirement.  If parts of it can be re-used, we certainly should aim to do so.

**Comment by roee88** [comment]
Is it decided that this is a connector and not built-in?

**Comment by simanadler** [comment]
@roee88 No, part of this task is to do the design and make that decision.
