### ISSUE TITLE
Smart Blueprint: Create Default and Example Hard Config Policies

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#795]
Create default policies needed for read and ingest flows.
Create example policies based on customer use cases, and/or those defined in the [config policy design doc](https://docs.google.com/document/d/1l7TmlacPjXGQJ_83OiJHYa40P_SL-YiQgxAcZqzyr_M/edit?usp=sharing)

Create a "how to" document describing how to write hard config policies.

Parent Issues: Issue #614, #93

**Comment by shlomitk1** [comment]
https://docs.google.com/document/d/1Tt8OEDifGJmmtzGmr9yloTHhtEjdPw2g6Io6aHeTeYg/edit?usp=sharing
cc @simanadler @roee88 @froesef @ronenkat @revit13

**Comment by simanadler** [comment]
@shlomitk1 This was closed in December.  Right?

**Comment by shlomitk1** [comment]
> @shlomitk1 This was closed in December. Right?

Right.
