### ISSUE TITLE
Smart Blueprint: Create Mechanism for Storing Infrastructure Metadata

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#797]
As described in section 4 of the [Smart Blueprint Approach document](https://docs.google.com/document/d/1s2kQfGoolhjdX2HZQxK_iBhV-9tAZ109MgpwybEZifo/edit?usp=sharing), config policies may contain predicate and decisions relating to the infrastructure (clusters, storage, network, etc).  Some of the infrastructure metadata may be static and some may be dynamic.  Either way, the most current values must be stored somewhere so that they may be queried by the control plane when making decisions about how best to construct the data plane for a given workload.

Assumptions:
* For now the values will be entered manually.  Real time monitoring of the values of the attributes is outside the scope of fybrik.

Parent Issues: #93

**Comment by simanadler** [comment]
It was decided to store in json format in a configmap.  Need to create a wrapper in the code in case we change the persistence in the future.  A taxonomy will describe the structure.  **Configmap has a limitation of 1M.**  Persistent storage is another option, but is more complicated.  For now we'll stay with configmap. 

Assumption is that this information is global, and not specific to a particular user or workload.

**Comment by YingchaoDu** [comment]
Attached is the Json draft. Please feel free to leave your comments @shlomitk1 @roee88 @simanadler. Thanks 
[Json-draft.pptx](https://github.com/fybrik/fybrik/files/7839702/Json-draft.pptx)

**Comment by shlomitk1** [comment]
Implemented.
