### ISSUE TITLE
Revisit error returned if WorkloadGeography not set when selecting module instance

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#812]
Reported by @simanadler 

Current code returns with an error if WorkloadGeography is unknown when selecting module instance (in `moduleinstance.go`):

`if m.WorkloadGeography, err = m.GetProcessingGeography(appContext); err != nil {`

The question was if it is really an error, or perhaps just a warning, or whether it's appropriate to check here at all. If there are no rules in the policy manager about geography, then in theory we wouldn't need this. right?

**Comment by roee88** [comment]
In which case is workload geo unknown?

**Comment by shlomitk1** [comment]
Implemented in #921
