### ISSUE TITLE
Hardcoded "fybrik-blueprint" namespace found in code

### ISSUE THREAD

**Issue by laurieaw63** [fybrik/fybrik#829]
Use the utils.GetBlueprintNamespace() method when referencing the blueprint namespace in the code. Found the following that is using hard-coded name which breaks tests in some environments.

fqdn := utils.GenerateModuleEndpointFQDN(releaseName, BlueprintNamespace)

Where BlueprintNamespace is a const in plotter.go

Fixing shortly.

**Comment by roee88** [comment]
Thanks for the fix
