### ISSUE TITLE
[opa] allow defining default policy at installation time

### ISSUE THREAD

**Issue by roee88** [fybrik/fybrik#882]
Currently set to deny by default. Should add an option to change to allow by default.

---

Note: allow is equivalent to `{}` so currently one can write the following rule to change the default to allow:

```rego
rule[{}]
```

You can also add conditions like:
```rego
rule[{}] {
 // conditions here
}
```
That would make it allow only if the conditions match and no other rule said otherwise (e.g., no other rule said that we should redact a column).

**Comment by revit13** [comment]
@roee88 does the existing opaServer.bootstrapPolicies field implements the above?
https://github.com/fybrik/fybrik/blob/master/charts/fybrik/values.yaml#L277

**Comment by roee88** [comment]
Is it clear to end users that the default is deny and what they can do to change it to allow? Is it easy to change to allow?
