### ISSUE TITLE
update Manager documentation

### ISSUE THREAD

**Issue by cdoron** [fybrik/fybrik#892]
in https://github.com/cdoron/fybrik/blob/master/manager/README.md :

1. [x] the documentation should reflect that one needs to copy `charts/fybrik/files/taxonomy` to `/tmp`
2. [x] `MAIN_POLICY_MANAGER_CONNECTOR_URL="http://localhost:49153"` (the `http://` prefix is missing)

**Comment by roee88** [comment]
Completed in #935
