### ISSUE TITLE
Manager: Generate log information in a standardized manner

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#926]
### Discussed in https://github.com/fybrik/fybrik/discussions/890

Create a single log structure to be used by both the control plane and the data plane components as is described in the [visibility high level design document](https://docs.google.com/document/d/1x3Jnp3CIN6YhJKtWM1uIimaw9-q6Hb9M7LqkazmBRBo/edit?usp=sharing).

Steps:

- [x] Define the log entry structure and make it available to all components 
- [x] Update the contributing documenation to include a section about logging
- [x] Change the fybrik manager to generate log entries according to the new structure
- [x] Change the fybrik manager to log all changes to fybrikapplication and fybrikapplication status
- [x] Change the fybrik manager to log all config maps used when it is deployed - i.e. log config map read when manager starts up

Connectors and data plane component updates are addressed in separate issues. #982 and #983

@laurieaw63 @ronenkat @roee88 @revit13 @cdoron @shlomitk1 @rohithdv @ritwikc Please comment on both the newly defined structure and the task list.

**Comment by roee88** [comment]
> (taxonomy?)

I think that it would be more appropriate to start with a code style section in the developer's guide and add logging guidelines to it (alongside other guidelines in the future).  For go code we can add something to pkg/logging but for 3rd parties we got the guidelines covering it. Otherwise, the complexity and overhead of logging might be too high.

**Comment by simanadler** [comment]
> > (taxonomy?)
> 
> I think that it would be more appropriate to start with a code style section in the developer's guide and add logging guidelines to it (alongside other guidelines in the future). For go code we can add something to pkg/logging but for 3rd parties we got the guidelines covering it. Otherwise, the complexity and overhead of logging might be too high. Is there anything in opentelemetry that can help here in the future?

OK.  Makes sense.  Updated the tasks in the issue.

**Comment by shlomitk1** [comment]
@simanadler We don't have credential manager connectors. Please remove from the task list.

**Comment by ronenkat** [comment]
> @simanadler We don't have credential manager connectors. Please remove from the task list.

We have Vault back-end plug-ins. They should provide logging as well.

**Comment by roee88** [comment]
> > @simanadler We don't have credential manager connectors. Please remove from the task list.
> 
> We have Vault back-end plug-ins. They should provide logging as well.

I think that this might be out of scope / different issue. It is inherently different than anything else in this list (does have the same context) and vault probably has its own logging for tracking who accessed what secret.

**Comment by shlomitk1** [comment]
>  Change the fybrik manager to log all config maps used when it is deployed
Each component (manager, connectors) can log the environment variables that come from the relevant config map.

**Comment by revit13** [comment]
I guess that the blueprint controller needs to pass additional information to the modules for the logging (such as workload_id etc).

**Comment by shlomitk1** [comment]
> 
> 
> I guess that the blueprint controller needs to pass additional information to the modules for the logging (such as workload_id etc).

Yes, to the connectors as well.

**Comment by simanadler** [comment]
> @simanadler We don't have credential manager connectors. Please remove from the task list.

Removed it

**Comment by shlomitk1** [comment]
Follow-up tasks:
1. Change label to fybrik-application-uuid instead of FybrikApplicationUUID.
2. Add uuid to unit tests, it is currently empty.
3. Add uuid to adminconfig policy evaluator (no value is currently passed to the evaluator input)

**Comment by shlomitk1** [comment]
All tasks are implemented.
