### ISSUE TITLE
Task: modify the spec of FybrikStorageAccount CR

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#963]
1. We need a way to identify a storage account. This identification will be used in an infrastructure object (to specify storage costs, for example) as well as in admin config policies to constrain the storage accounts that can be used. 
Proposal: to add an ID field in the spec of FybrikStorageAccount CR.
2. Pair an endpoint with a region instead of the current spec that has one endpoint for multiple regions.

**Comment by simanadler** [comment]
> 1. We need a way to identify a storage account. This identification will be used in an infrastructure object (to specify storage costs, for example) as well as in admin config policies to constrain the storage accounts that can be used.
>        Proposal: to add an ID field in the spec of FybrikStorageAccount CR.
Can we / should we use labels rather than adding an ID field?  
If you feel we need a cluster-wide unique id (over time) what about the k8s UID?

> 
>     2. Pair an endpoint with a region instead of the current spec that has one endpoint for multiple regions.

Why does the current implementation map the endpoint to multiple regions?
