### ISSUE TITLE
Task: respect module restrictions while selecting a module

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#964]
Admin config policies may affect the choice of the selected modules by applying some constraints on them, for example: module type should be `plugin`, or scope should be `workload`. However, the current implementation ignores module restrictions while selecting a module.

**Comment by simanadler** [comment]
@shlomitk1 I don't think it's necessary to address this in the current implementation.  Once hard configs are introduced and we remove the hard coded logic this will be addressed.
