### ISSUE TITLE
Add conditions to FybrikModule

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#966]
Proposal: modify FybrikModuleStatus to use Ready and Error conditions instead of ValidModule and ErrorMessage fields.
``` 
type Condition struct {
	// Type of the condition
	Type ConditionType `json:"type"`
	// Status of the condition: true or false
	Status corev1.ConditionStatus `json:"status"`
	// Message contains the details of the current condition
	// +optional
	Message string `json:"message,omitempty"`
}
```

**Comment by simanadler** [comment]
@shlomitk1 Is the intent that "ready" means that the module passed validation?  Using that term could be misleading since one could think that it means that the service described by the module is ready, which is not something we check.  Perhaps valid and errors? @roytman @ronenkat your thoughts?

**Comment by shlomitk1** [comment]
valid is fine. I don't think we need an error condition because Valid with status false and an appropriate message means exactly that, it is not a separate condition.
