### ISSUE TITLE
Manager: Standardize Logging

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#981]
### Discussed in https://github.com/fybrik/fybrik/discussions/890

Implement the new logging approach as detailed in the [logging approach document](https://docs.google.com/document/d/1x3Jnp3CIN6YhJKtWM1uIimaw9-q6Hb9M7LqkazmBRBo/edit?usp=sharing). 

The golang logging structure and helper functions should be built such that they can be used by the control plane as well as in a stand-alone fashion by connectors and data plane services.

- [x] Implement golang logging structure and helper functions for use by control plane, and by data plane components and connectors
- [x] Update control plane to use new logging
- [x] Update open source connectors to use new logging
- [x] Update open source arrow-flight component to use new logging
- [ ] Update data movement operator to use new logging - moved to backlog
- [ ] Implement java fybrik logging library for data plane components and connectors - moved to backlog
- [x] Implement python java logging library for data plane components and connectors

**Comment by roytman** [comment]
I'd suggest to review this task with

**Comment by roytman** [comment]
@simanadler, can we close it?

**Comment by simanadler** [comment]
I moved the changes to the logging in the data movement operator and the creation of a java logging library  to product backlog, and am closing this.
