### ISSUE TITLE
Connectors: Generate log information in a standardized manner

### ISSUE THREAD

**Issue by simanadler** [fybrik/fybrik#982]
### Discussed in https://github.com/fybrik/fybrik/discussions/890

Create a single log structure to be used by both the control plane and the data plane components as is described in the [visibility high level design document](https://docs.google.com/document/d/1x3Jnp3CIN6YhJKtWM1uIimaw9-q6Hb9M7LqkazmBRBo/edit?usp=sharing).

- [x] Change the data catalog connectors to generate log entries according to the new structure
- [ ] Change the data policy connectors to generate log entries according to the new structure

**Comment by roytman** [comment]
@simanadler, can we close it?

**Comment by simanadler** [comment]
@roytman Have the open source connectors been updated to use the standardized logging?

**Comment by roytman** [comment]
Katalog connector has been, I checked the OPA connector, and it doesn't contain any log calls. probably it is a separate issue.

**Comment by roytman** [comment]
closing the issue.
