### ISSUE TITLE
Create a list of environment variables used by fybrik

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#999]
Create a list of environment variables used by fybrik. It can be published on [fybrik.io](https://fybrik.io/) under references.

**Comment by shlomitk1** [comment]
Environment variables used for Fybrik deployment? Or environment variables used by various pods in the control plane within configmaps and secrets?

**Comment by roytman** [comment]
I meant environment variables used for Fybrik development and deployment. (if any)

**Comment by roytman** [comment]
close for now.
